// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: runtime_service.proto

#include "runtime_service.pb.h"
#include "runtime_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace runtime {
namespace v1alpha2 {

static const char* RuntimeService_method_names[] = {
  "/runtime.v1alpha2.RuntimeService/CreatePod",
  "/runtime.v1alpha2.RuntimeService/DeletePod",
  "/runtime.v1alpha2.RuntimeService/ListPods",
  "/runtime.v1alpha2.RuntimeService/StartPod",
  "/runtime.v1alpha2.RuntimeService/StopPod",
  "/runtime.v1alpha2.RuntimeService/CreateContainer",
  "/runtime.v1alpha2.RuntimeService/DeleteContainer",
  "/runtime.v1alpha2.RuntimeService/ListContainers",
  "/runtime.v1alpha2.RuntimeService/StartContainer",
  "/runtime.v1alpha2.RuntimeService/StopContainer",
};

std::unique_ptr< RuntimeService::Stub> RuntimeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RuntimeService::Stub> stub(new RuntimeService::Stub(channel));
  return stub;
}

RuntimeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_CreatePod_(RuntimeService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeletePod_(RuntimeService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListPods_(RuntimeService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StartPod_(RuntimeService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopPod_(RuntimeService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateContainer_(RuntimeService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteContainer_(RuntimeService_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListContainers_(RuntimeService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StartContainer_(RuntimeService_method_names[8], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopContainer_(RuntimeService_method_names[9], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RuntimeService::Stub::CreatePod(::grpc::ClientContext* context, const ::runtime::v1alpha2::CreatePodRequest& request, ::runtime::v1alpha2::CreatePodResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreatePod_, context, request, response);
}

void RuntimeService::Stub::experimental_async::CreatePod(::grpc::ClientContext* context, const ::runtime::v1alpha2::CreatePodRequest* request, ::runtime::v1alpha2::CreatePodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreatePod_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::CreatePod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::CreatePodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreatePod_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::CreatePod(::grpc::ClientContext* context, const ::runtime::v1alpha2::CreatePodRequest* request, ::runtime::v1alpha2::CreatePodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreatePod_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::CreatePod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::CreatePodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreatePod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::CreatePodResponse>* RuntimeService::Stub::AsyncCreatePodRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::CreatePodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::CreatePodResponse>::Create(channel_.get(), cq, rpcmethod_CreatePod_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::CreatePodResponse>* RuntimeService::Stub::PrepareAsyncCreatePodRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::CreatePodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::CreatePodResponse>::Create(channel_.get(), cq, rpcmethod_CreatePod_, context, request, false);
}

::grpc::Status RuntimeService::Stub::DeletePod(::grpc::ClientContext* context, const ::runtime::v1alpha2::DeletePodRequest& request, ::runtime::v1alpha2::DeletePodResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DeletePod_, context, request, response);
}

void RuntimeService::Stub::experimental_async::DeletePod(::grpc::ClientContext* context, const ::runtime::v1alpha2::DeletePodRequest* request, ::runtime::v1alpha2::DeletePodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeletePod_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::DeletePod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::DeletePodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeletePod_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::DeletePod(::grpc::ClientContext* context, const ::runtime::v1alpha2::DeletePodRequest* request, ::runtime::v1alpha2::DeletePodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DeletePod_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::DeletePod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::DeletePodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DeletePod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::DeletePodResponse>* RuntimeService::Stub::AsyncDeletePodRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::DeletePodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::DeletePodResponse>::Create(channel_.get(), cq, rpcmethod_DeletePod_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::DeletePodResponse>* RuntimeService::Stub::PrepareAsyncDeletePodRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::DeletePodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::DeletePodResponse>::Create(channel_.get(), cq, rpcmethod_DeletePod_, context, request, false);
}

::grpc::Status RuntimeService::Stub::ListPods(::grpc::ClientContext* context, const ::runtime::v1alpha2::ListPodRequest& request, ::runtime::v1alpha2::ListPodResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ListPods_, context, request, response);
}

void RuntimeService::Stub::experimental_async::ListPods(::grpc::ClientContext* context, const ::runtime::v1alpha2::ListPodRequest* request, ::runtime::v1alpha2::ListPodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListPods_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::ListPods(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::ListPodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListPods_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::ListPods(::grpc::ClientContext* context, const ::runtime::v1alpha2::ListPodRequest* request, ::runtime::v1alpha2::ListPodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ListPods_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::ListPods(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::ListPodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ListPods_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::ListPodResponse>* RuntimeService::Stub::AsyncListPodsRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::ListPodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::ListPodResponse>::Create(channel_.get(), cq, rpcmethod_ListPods_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::ListPodResponse>* RuntimeService::Stub::PrepareAsyncListPodsRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::ListPodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::ListPodResponse>::Create(channel_.get(), cq, rpcmethod_ListPods_, context, request, false);
}

::grpc::Status RuntimeService::Stub::StartPod(::grpc::ClientContext* context, const ::runtime::v1alpha2::StartPodRequest& request, ::runtime::v1alpha2::StartPodResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StartPod_, context, request, response);
}

void RuntimeService::Stub::experimental_async::StartPod(::grpc::ClientContext* context, const ::runtime::v1alpha2::StartPodRequest* request, ::runtime::v1alpha2::StartPodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartPod_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::StartPod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::StartPodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartPod_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::StartPod(::grpc::ClientContext* context, const ::runtime::v1alpha2::StartPodRequest* request, ::runtime::v1alpha2::StartPodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartPod_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::StartPod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::StartPodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartPod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::StartPodResponse>* RuntimeService::Stub::AsyncStartPodRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::StartPodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::StartPodResponse>::Create(channel_.get(), cq, rpcmethod_StartPod_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::StartPodResponse>* RuntimeService::Stub::PrepareAsyncStartPodRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::StartPodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::StartPodResponse>::Create(channel_.get(), cq, rpcmethod_StartPod_, context, request, false);
}

::grpc::Status RuntimeService::Stub::StopPod(::grpc::ClientContext* context, const ::runtime::v1alpha2::StopPodRequest& request, ::runtime::v1alpha2::StopPodResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StopPod_, context, request, response);
}

void RuntimeService::Stub::experimental_async::StopPod(::grpc::ClientContext* context, const ::runtime::v1alpha2::StopPodRequest* request, ::runtime::v1alpha2::StopPodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StopPod_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::StopPod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::StopPodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StopPod_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::StopPod(::grpc::ClientContext* context, const ::runtime::v1alpha2::StopPodRequest* request, ::runtime::v1alpha2::StopPodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StopPod_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::StopPod(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::StopPodResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StopPod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::StopPodResponse>* RuntimeService::Stub::AsyncStopPodRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::StopPodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::StopPodResponse>::Create(channel_.get(), cq, rpcmethod_StopPod_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::StopPodResponse>* RuntimeService::Stub::PrepareAsyncStopPodRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::StopPodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::StopPodResponse>::Create(channel_.get(), cq, rpcmethod_StopPod_, context, request, false);
}

::grpc::Status RuntimeService::Stub::CreateContainer(::grpc::ClientContext* context, const ::runtime::v1alpha2::CreateContainerRequest& request, ::runtime::v1alpha2::CreateContainerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateContainer_, context, request, response);
}

void RuntimeService::Stub::experimental_async::CreateContainer(::grpc::ClientContext* context, const ::runtime::v1alpha2::CreateContainerRequest* request, ::runtime::v1alpha2::CreateContainerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateContainer_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::CreateContainer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::CreateContainerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateContainer_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::CreateContainer(::grpc::ClientContext* context, const ::runtime::v1alpha2::CreateContainerRequest* request, ::runtime::v1alpha2::CreateContainerResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateContainer_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::CreateContainer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::CreateContainerResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateContainer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::CreateContainerResponse>* RuntimeService::Stub::AsyncCreateContainerRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::CreateContainerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::CreateContainerResponse>::Create(channel_.get(), cq, rpcmethod_CreateContainer_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::CreateContainerResponse>* RuntimeService::Stub::PrepareAsyncCreateContainerRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::CreateContainerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::CreateContainerResponse>::Create(channel_.get(), cq, rpcmethod_CreateContainer_, context, request, false);
}

::grpc::Status RuntimeService::Stub::DeleteContainer(::grpc::ClientContext* context, const ::runtime::v1alpha2::DeleteContainerRequest& request, ::runtime::v1alpha2::DeleteContainerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DeleteContainer_, context, request, response);
}

void RuntimeService::Stub::experimental_async::DeleteContainer(::grpc::ClientContext* context, const ::runtime::v1alpha2::DeleteContainerRequest* request, ::runtime::v1alpha2::DeleteContainerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeleteContainer_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::DeleteContainer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::DeleteContainerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DeleteContainer_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::DeleteContainer(::grpc::ClientContext* context, const ::runtime::v1alpha2::DeleteContainerRequest* request, ::runtime::v1alpha2::DeleteContainerResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DeleteContainer_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::DeleteContainer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::DeleteContainerResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DeleteContainer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::DeleteContainerResponse>* RuntimeService::Stub::AsyncDeleteContainerRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::DeleteContainerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::DeleteContainerResponse>::Create(channel_.get(), cq, rpcmethod_DeleteContainer_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::DeleteContainerResponse>* RuntimeService::Stub::PrepareAsyncDeleteContainerRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::DeleteContainerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::DeleteContainerResponse>::Create(channel_.get(), cq, rpcmethod_DeleteContainer_, context, request, false);
}

::grpc::Status RuntimeService::Stub::ListContainers(::grpc::ClientContext* context, const ::runtime::v1alpha2::ListContainersRequest& request, ::runtime::v1alpha2::ListContainersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ListContainers_, context, request, response);
}

void RuntimeService::Stub::experimental_async::ListContainers(::grpc::ClientContext* context, const ::runtime::v1alpha2::ListContainersRequest* request, ::runtime::v1alpha2::ListContainersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListContainers_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::ListContainers(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::ListContainersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListContainers_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::ListContainers(::grpc::ClientContext* context, const ::runtime::v1alpha2::ListContainersRequest* request, ::runtime::v1alpha2::ListContainersResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ListContainers_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::ListContainers(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::ListContainersResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ListContainers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::ListContainersResponse>* RuntimeService::Stub::AsyncListContainersRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::ListContainersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::ListContainersResponse>::Create(channel_.get(), cq, rpcmethod_ListContainers_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::ListContainersResponse>* RuntimeService::Stub::PrepareAsyncListContainersRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::ListContainersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::ListContainersResponse>::Create(channel_.get(), cq, rpcmethod_ListContainers_, context, request, false);
}

::grpc::Status RuntimeService::Stub::StartContainer(::grpc::ClientContext* context, const ::runtime::v1alpha2::StartContainerRequest& request, ::runtime::v1alpha2::StartContainerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StartContainer_, context, request, response);
}

void RuntimeService::Stub::experimental_async::StartContainer(::grpc::ClientContext* context, const ::runtime::v1alpha2::StartContainerRequest* request, ::runtime::v1alpha2::StartContainerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartContainer_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::StartContainer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::StartContainerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StartContainer_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::StartContainer(::grpc::ClientContext* context, const ::runtime::v1alpha2::StartContainerRequest* request, ::runtime::v1alpha2::StartContainerResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartContainer_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::StartContainer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::StartContainerResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StartContainer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::StartContainerResponse>* RuntimeService::Stub::AsyncStartContainerRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::StartContainerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::StartContainerResponse>::Create(channel_.get(), cq, rpcmethod_StartContainer_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::StartContainerResponse>* RuntimeService::Stub::PrepareAsyncStartContainerRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::StartContainerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::StartContainerResponse>::Create(channel_.get(), cq, rpcmethod_StartContainer_, context, request, false);
}

::grpc::Status RuntimeService::Stub::StopContainer(::grpc::ClientContext* context, const ::runtime::v1alpha2::StopContainerRequest& request, ::runtime::v1alpha2::StopContainerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StopContainer_, context, request, response);
}

void RuntimeService::Stub::experimental_async::StopContainer(::grpc::ClientContext* context, const ::runtime::v1alpha2::StopContainerRequest* request, ::runtime::v1alpha2::StopContainerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StopContainer_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::StopContainer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::StopContainerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_StopContainer_, context, request, response, std::move(f));
}

void RuntimeService::Stub::experimental_async::StopContainer(::grpc::ClientContext* context, const ::runtime::v1alpha2::StopContainerRequest* request, ::runtime::v1alpha2::StopContainerResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StopContainer_, context, request, response, reactor);
}

void RuntimeService::Stub::experimental_async::StopContainer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::runtime::v1alpha2::StopContainerResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_StopContainer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::StopContainerResponse>* RuntimeService::Stub::AsyncStopContainerRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::StopContainerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::StopContainerResponse>::Create(channel_.get(), cq, rpcmethod_StopContainer_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::runtime::v1alpha2::StopContainerResponse>* RuntimeService::Stub::PrepareAsyncStopContainerRaw(::grpc::ClientContext* context, const ::runtime::v1alpha2::StopContainerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::runtime::v1alpha2::StopContainerResponse>::Create(channel_.get(), cq, rpcmethod_StopContainer_, context, request, false);
}

RuntimeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::v1alpha2::CreatePodRequest, ::runtime::v1alpha2::CreatePodResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::runtime::v1alpha2::CreatePodRequest* req,
             ::runtime::v1alpha2::CreatePodResponse* resp) {
               return service->CreatePod(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::v1alpha2::DeletePodRequest, ::runtime::v1alpha2::DeletePodResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::runtime::v1alpha2::DeletePodRequest* req,
             ::runtime::v1alpha2::DeletePodResponse* resp) {
               return service->DeletePod(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::v1alpha2::ListPodRequest, ::runtime::v1alpha2::ListPodResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::runtime::v1alpha2::ListPodRequest* req,
             ::runtime::v1alpha2::ListPodResponse* resp) {
               return service->ListPods(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::v1alpha2::StartPodRequest, ::runtime::v1alpha2::StartPodResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::runtime::v1alpha2::StartPodRequest* req,
             ::runtime::v1alpha2::StartPodResponse* resp) {
               return service->StartPod(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::v1alpha2::StopPodRequest, ::runtime::v1alpha2::StopPodResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::runtime::v1alpha2::StopPodRequest* req,
             ::runtime::v1alpha2::StopPodResponse* resp) {
               return service->StopPod(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::v1alpha2::CreateContainerRequest, ::runtime::v1alpha2::CreateContainerResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::runtime::v1alpha2::CreateContainerRequest* req,
             ::runtime::v1alpha2::CreateContainerResponse* resp) {
               return service->CreateContainer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::v1alpha2::DeleteContainerRequest, ::runtime::v1alpha2::DeleteContainerResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::runtime::v1alpha2::DeleteContainerRequest* req,
             ::runtime::v1alpha2::DeleteContainerResponse* resp) {
               return service->DeleteContainer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::v1alpha2::ListContainersRequest, ::runtime::v1alpha2::ListContainersResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::runtime::v1alpha2::ListContainersRequest* req,
             ::runtime::v1alpha2::ListContainersResponse* resp) {
               return service->ListContainers(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::v1alpha2::StartContainerRequest, ::runtime::v1alpha2::StartContainerResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::runtime::v1alpha2::StartContainerRequest* req,
             ::runtime::v1alpha2::StartContainerResponse* resp) {
               return service->StartContainer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::v1alpha2::StopContainerRequest, ::runtime::v1alpha2::StopContainerResponse>(
          [](RuntimeService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::runtime::v1alpha2::StopContainerRequest* req,
             ::runtime::v1alpha2::StopContainerResponse* resp) {
               return service->StopContainer(ctx, req, resp);
             }, this)));
}

RuntimeService::Service::~Service() {
}

::grpc::Status RuntimeService::Service::CreatePod(::grpc::ServerContext* context, const ::runtime::v1alpha2::CreatePodRequest* request, ::runtime::v1alpha2::CreatePodResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::DeletePod(::grpc::ServerContext* context, const ::runtime::v1alpha2::DeletePodRequest* request, ::runtime::v1alpha2::DeletePodResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::ListPods(::grpc::ServerContext* context, const ::runtime::v1alpha2::ListPodRequest* request, ::runtime::v1alpha2::ListPodResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::StartPod(::grpc::ServerContext* context, const ::runtime::v1alpha2::StartPodRequest* request, ::runtime::v1alpha2::StartPodResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::StopPod(::grpc::ServerContext* context, const ::runtime::v1alpha2::StopPodRequest* request, ::runtime::v1alpha2::StopPodResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::CreateContainer(::grpc::ServerContext* context, const ::runtime::v1alpha2::CreateContainerRequest* request, ::runtime::v1alpha2::CreateContainerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::DeleteContainer(::grpc::ServerContext* context, const ::runtime::v1alpha2::DeleteContainerRequest* request, ::runtime::v1alpha2::DeleteContainerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::ListContainers(::grpc::ServerContext* context, const ::runtime::v1alpha2::ListContainersRequest* request, ::runtime::v1alpha2::ListContainersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::StartContainer(::grpc::ServerContext* context, const ::runtime::v1alpha2::StartContainerRequest* request, ::runtime::v1alpha2::StartContainerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::StopContainer(::grpc::ServerContext* context, const ::runtime::v1alpha2::StopContainerRequest* request, ::runtime::v1alpha2::StopContainerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace runtime
}  // namespace v1alpha2

