/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: runtime_service.proto */

#ifndef PROTOBUF_C_runtime_5fservice_2eproto__INCLUDED
#define PROTOBUF_C_runtime_5fservice_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Runtime__V1alpha2__DNSConfig Runtime__V1alpha2__DNSConfig;
typedef struct _Runtime__V1alpha2__PortMapping Runtime__V1alpha2__PortMapping;
typedef struct _Runtime__V1alpha2__LinuxPodSandboxConfig Runtime__V1alpha2__LinuxPodSandboxConfig;
typedef struct _Runtime__V1alpha2__LinuxPodSandboxConfig__SysctlsEntry Runtime__V1alpha2__LinuxPodSandboxConfig__SysctlsEntry;
typedef struct _Runtime__V1alpha2__PodSandboxConfig Runtime__V1alpha2__PodSandboxConfig;
typedef struct _Runtime__V1alpha2__PodSandboxConfig__LabelsEntry Runtime__V1alpha2__PodSandboxConfig__LabelsEntry;
typedef struct _Runtime__V1alpha2__PodSandboxConfig__AnnotationsEntry Runtime__V1alpha2__PodSandboxConfig__AnnotationsEntry;
typedef struct _Runtime__V1alpha2__PodMetadata Runtime__V1alpha2__PodMetadata;
typedef struct _Runtime__V1alpha2__NetworkConfig Runtime__V1alpha2__NetworkConfig;
typedef struct _Runtime__V1alpha2__LinuxConfig Runtime__V1alpha2__LinuxConfig;
typedef struct _Runtime__V1alpha2__LinuxConfig__SysctlsEntry Runtime__V1alpha2__LinuxConfig__SysctlsEntry;
typedef struct _Runtime__V1alpha2__SecurityContext Runtime__V1alpha2__SecurityContext;
typedef struct _Runtime__V1alpha2__NamespaceOption Runtime__V1alpha2__NamespaceOption;
typedef struct _Runtime__V1alpha2__SELinuxOption Runtime__V1alpha2__SELinuxOption;
typedef struct _Runtime__V1alpha2__RunAsUserOption Runtime__V1alpha2__RunAsUserOption;
typedef struct _Runtime__V1alpha2__CreatePodRequest Runtime__V1alpha2__CreatePodRequest;
typedef struct _Runtime__V1alpha2__CreatePodResponse Runtime__V1alpha2__CreatePodResponse;
typedef struct _Runtime__V1alpha2__DeletePodRequest Runtime__V1alpha2__DeletePodRequest;
typedef struct _Runtime__V1alpha2__DeletePodResponse Runtime__V1alpha2__DeletePodResponse;
typedef struct _Runtime__V1alpha2__ListPodRequest Runtime__V1alpha2__ListPodRequest;
typedef struct _Runtime__V1alpha2__PodFilter Runtime__V1alpha2__PodFilter;
typedef struct _Runtime__V1alpha2__PodFilter__LabelSelectorEntry Runtime__V1alpha2__PodFilter__LabelSelectorEntry;
typedef struct _Runtime__V1alpha2__ListPodResponse Runtime__V1alpha2__ListPodResponse;
typedef struct _Runtime__V1alpha2__Pod Runtime__V1alpha2__Pod;
typedef struct _Runtime__V1alpha2__Pod__LabelsEntry Runtime__V1alpha2__Pod__LabelsEntry;
typedef struct _Runtime__V1alpha2__Pod__AnnotationsEntry Runtime__V1alpha2__Pod__AnnotationsEntry;
typedef struct _Runtime__V1alpha2__StartPodRequest Runtime__V1alpha2__StartPodRequest;
typedef struct _Runtime__V1alpha2__StartPodResponse Runtime__V1alpha2__StartPodResponse;
typedef struct _Runtime__V1alpha2__StopPodRequest Runtime__V1alpha2__StopPodRequest;
typedef struct _Runtime__V1alpha2__StopPodResponse Runtime__V1alpha2__StopPodResponse;
typedef struct _Runtime__V1alpha2__ContainerConfig Runtime__V1alpha2__ContainerConfig;
typedef struct _Runtime__V1alpha2__ContainerConfig__LabelsEntry Runtime__V1alpha2__ContainerConfig__LabelsEntry;
typedef struct _Runtime__V1alpha2__ContainerConfig__AnnotationsEntry Runtime__V1alpha2__ContainerConfig__AnnotationsEntry;
typedef struct _Runtime__V1alpha2__ContainerMetadata Runtime__V1alpha2__ContainerMetadata;
typedef struct _Runtime__V1alpha2__ImageSpec Runtime__V1alpha2__ImageSpec;
typedef struct _Runtime__V1alpha2__KeyValue Runtime__V1alpha2__KeyValue;
typedef struct _Runtime__V1alpha2__Mount Runtime__V1alpha2__Mount;
typedef struct _Runtime__V1alpha2__CreateContainerRequest Runtime__V1alpha2__CreateContainerRequest;
typedef struct _Runtime__V1alpha2__CreateContainerResponse Runtime__V1alpha2__CreateContainerResponse;
typedef struct _Runtime__V1alpha2__DeleteContainerRequest Runtime__V1alpha2__DeleteContainerRequest;
typedef struct _Runtime__V1alpha2__DeleteContainerResponse Runtime__V1alpha2__DeleteContainerResponse;
typedef struct _Runtime__V1alpha2__ListContainersRequest Runtime__V1alpha2__ListContainersRequest;
typedef struct _Runtime__V1alpha2__ContainerFilter Runtime__V1alpha2__ContainerFilter;
typedef struct _Runtime__V1alpha2__ContainerFilter__LabelSelectorEntry Runtime__V1alpha2__ContainerFilter__LabelSelectorEntry;
typedef struct _Runtime__V1alpha2__ListContainersResponse Runtime__V1alpha2__ListContainersResponse;
typedef struct _Runtime__V1alpha2__Container Runtime__V1alpha2__Container;
typedef struct _Runtime__V1alpha2__Container__LabelsEntry Runtime__V1alpha2__Container__LabelsEntry;
typedef struct _Runtime__V1alpha2__Container__AnnotationsEntry Runtime__V1alpha2__Container__AnnotationsEntry;
typedef struct _Runtime__V1alpha2__StartContainerRequest Runtime__V1alpha2__StartContainerRequest;
typedef struct _Runtime__V1alpha2__StartContainerResponse Runtime__V1alpha2__StartContainerResponse;
typedef struct _Runtime__V1alpha2__StopContainerRequest Runtime__V1alpha2__StopContainerRequest;
typedef struct _Runtime__V1alpha2__StopContainerResponse Runtime__V1alpha2__StopContainerResponse;


/* --- enums --- */

typedef enum _Runtime__V1alpha2__PodState {
  RUNTIME__V1ALPHA2__POD_STATE__UNKNOWN = 0,
  RUNTIME__V1ALPHA2__POD_STATE__CREATED = 1,
  RUNTIME__V1ALPHA2__POD_STATE__RUNNING = 2,
  RUNTIME__V1ALPHA2__POD_STATE__STOPPED = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RUNTIME__V1ALPHA2__POD_STATE)
} Runtime__V1alpha2__PodState;
typedef enum _Runtime__V1alpha2__ContainerState {
  RUNTIME__V1ALPHA2__CONTAINER_STATE__CONTAINER_UNKNOWN = 0,
  RUNTIME__V1ALPHA2__CONTAINER_STATE__CONTAINER_CREATED = 1,
  RUNTIME__V1ALPHA2__CONTAINER_STATE__CONTAINER_RUNNING = 2,
  RUNTIME__V1ALPHA2__CONTAINER_STATE__CONTAINER_STOPPED = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RUNTIME__V1ALPHA2__CONTAINER_STATE)
} Runtime__V1alpha2__ContainerState;

/* --- messages --- */

struct  _Runtime__V1alpha2__DNSConfig
{
  ProtobufCMessage base;
  size_t n_servers;
  char **servers;
  size_t n_searches;
  char **searches;
  size_t n_options;
  char **options;
};
#define RUNTIME__V1ALPHA2__DNSCONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__dnsconfig__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL }


struct  _Runtime__V1alpha2__PortMapping
{
  ProtobufCMessage base;
  char *protocol;
  int32_t container_port;
  int32_t host_port;
  char *host_ip;
};
#define RUNTIME__V1ALPHA2__PORT_MAPPING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__port_mapping__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__LinuxPodSandboxConfig__SysctlsEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__LINUX_POD_SANDBOX_CONFIG__SYSCTLS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__linux_pod_sandbox_config__sysctls_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__LinuxPodSandboxConfig
{
  ProtobufCMessage base;
  char *cgroup_parent;
  Runtime__V1alpha2__SecurityContext *security_context;
  size_t n_sysctls;
  Runtime__V1alpha2__LinuxPodSandboxConfig__SysctlsEntry **sysctls;
};
#define RUNTIME__V1ALPHA2__LINUX_POD_SANDBOX_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__linux_pod_sandbox_config__descriptor) \
    , (char *)protobuf_c_empty_string, NULL, 0,NULL }


struct  _Runtime__V1alpha2__PodSandboxConfig__LabelsEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__POD_SANDBOX_CONFIG__LABELS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__pod_sandbox_config__labels_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__PodSandboxConfig__AnnotationsEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__POD_SANDBOX_CONFIG__ANNOTATIONS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__pod_sandbox_config__annotations_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * Pod messages
 */
struct  _Runtime__V1alpha2__PodSandboxConfig
{
  ProtobufCMessage base;
  Runtime__V1alpha2__PodMetadata *metadata;
  char *hostname;
  char *log_directory;
  Runtime__V1alpha2__DNSConfig *dns_config;
  size_t n_port_mappings;
  Runtime__V1alpha2__PortMapping **port_mappings;
  Runtime__V1alpha2__LinuxPodSandboxConfig *linux_config;
  size_t n_labels;
  Runtime__V1alpha2__PodSandboxConfig__LabelsEntry **labels;
  size_t n_annotations;
  Runtime__V1alpha2__PodSandboxConfig__AnnotationsEntry **annotations;
};
#define RUNTIME__V1ALPHA2__POD_SANDBOX_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__pod_sandbox_config__descriptor) \
    , NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, NULL, 0,NULL, NULL, 0,NULL, 0,NULL }


struct  _Runtime__V1alpha2__PodMetadata
{
  ProtobufCMessage base;
  char *name;
  char *uid;
  char *namespace_;
  uint32_t attempt;
};
#define RUNTIME__V1ALPHA2__POD_METADATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__pod_metadata__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  _Runtime__V1alpha2__NetworkConfig
{
  ProtobufCMessage base;
  char *pod_cidr;
};
#define RUNTIME__V1ALPHA2__NETWORK_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__network_config__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__LinuxConfig__SysctlsEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__LINUX_CONFIG__SYSCTLS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__linux_config__sysctls_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__LinuxConfig
{
  ProtobufCMessage base;
  char *cgroup_parent;
  Runtime__V1alpha2__SecurityContext *security_context;
  size_t n_sysctls;
  Runtime__V1alpha2__LinuxConfig__SysctlsEntry **sysctls;
};
#define RUNTIME__V1ALPHA2__LINUX_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__linux_config__descriptor) \
    , (char *)protobuf_c_empty_string, NULL, 0,NULL }


struct  _Runtime__V1alpha2__SecurityContext
{
  ProtobufCMessage base;
  Runtime__V1alpha2__NamespaceOption *namespace_options;
  Runtime__V1alpha2__SELinuxOption *selinux_options;
  Runtime__V1alpha2__RunAsUserOption *run_as_user;
  protobuf_c_boolean privileged;
};
#define RUNTIME__V1ALPHA2__SECURITY_CONTEXT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__security_context__descriptor) \
    , NULL, NULL, NULL, 0 }


struct  _Runtime__V1alpha2__NamespaceOption
{
  ProtobufCMessage base;
  protobuf_c_boolean host_network;
  protobuf_c_boolean host_pid;
  protobuf_c_boolean host_ipc;
};
#define RUNTIME__V1ALPHA2__NAMESPACE_OPTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__namespace_option__descriptor) \
    , 0, 0, 0 }


struct  _Runtime__V1alpha2__SELinuxOption
{
  ProtobufCMessage base;
  char *user;
  char *role;
  char *type;
  char *level;
};
#define RUNTIME__V1ALPHA2__SELINUX_OPTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__selinux_option__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__RunAsUserOption
{
  ProtobufCMessage base;
  int64_t uid;
  int64_t gid;
  size_t n_additional_gids;
  int64_t *additional_gids;
};
#define RUNTIME__V1ALPHA2__RUN_AS_USER_OPTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__run_as_user_option__descriptor) \
    , 0, 0, 0,NULL }


struct  _Runtime__V1alpha2__CreatePodRequest
{
  ProtobufCMessage base;
  Runtime__V1alpha2__PodSandboxConfig *config;
};
#define RUNTIME__V1ALPHA2__CREATE_POD_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__create_pod_request__descriptor) \
    , NULL }


struct  _Runtime__V1alpha2__CreatePodResponse
{
  ProtobufCMessage base;
  char *pod_sandbox_id;
};
#define RUNTIME__V1ALPHA2__CREATE_POD_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__create_pod_response__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__DeletePodRequest
{
  ProtobufCMessage base;
  char *pod_sandbox_id;
};
#define RUNTIME__V1ALPHA2__DELETE_POD_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__delete_pod_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__DeletePodResponse
{
  ProtobufCMessage base;
};
#define RUNTIME__V1ALPHA2__DELETE_POD_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__delete_pod_response__descriptor) \
     }


struct  _Runtime__V1alpha2__ListPodRequest
{
  ProtobufCMessage base;
  Runtime__V1alpha2__PodFilter *filter;
};
#define RUNTIME__V1ALPHA2__LIST_POD_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__list_pod_request__descriptor) \
    , NULL }


struct  _Runtime__V1alpha2__PodFilter__LabelSelectorEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__POD_FILTER__LABEL_SELECTOR_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__pod_filter__label_selector_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__PodFilter
{
  ProtobufCMessage base;
  char *id;
  Runtime__V1alpha2__PodState state;
  size_t n_label_selector;
  Runtime__V1alpha2__PodFilter__LabelSelectorEntry **label_selector;
};
#define RUNTIME__V1ALPHA2__POD_FILTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__pod_filter__descriptor) \
    , (char *)protobuf_c_empty_string, RUNTIME__V1ALPHA2__POD_STATE__UNKNOWN, 0,NULL }


struct  _Runtime__V1alpha2__ListPodResponse
{
  ProtobufCMessage base;
  size_t n_items;
  Runtime__V1alpha2__Pod **items;
};
#define RUNTIME__V1ALPHA2__LIST_POD_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__list_pod_response__descriptor) \
    , 0,NULL }


struct  _Runtime__V1alpha2__Pod__LabelsEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__POD__LABELS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__pod__labels_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__Pod__AnnotationsEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__POD__ANNOTATIONS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__pod__annotations_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__Pod
{
  ProtobufCMessage base;
  char *id;
  Runtime__V1alpha2__PodMetadata *metadata;
  Runtime__V1alpha2__PodState state;
  int64_t created_at;
  size_t n_labels;
  Runtime__V1alpha2__Pod__LabelsEntry **labels;
  size_t n_annotations;
  Runtime__V1alpha2__Pod__AnnotationsEntry **annotations;
};
#define RUNTIME__V1ALPHA2__POD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__pod__descriptor) \
    , (char *)protobuf_c_empty_string, NULL, RUNTIME__V1ALPHA2__POD_STATE__UNKNOWN, 0, 0,NULL, 0,NULL }


struct  _Runtime__V1alpha2__StartPodRequest
{
  ProtobufCMessage base;
  char *pod_sandbox_id;
};
#define RUNTIME__V1ALPHA2__START_POD_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__start_pod_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__StartPodResponse
{
  ProtobufCMessage base;
};
#define RUNTIME__V1ALPHA2__START_POD_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__start_pod_response__descriptor) \
     }


struct  _Runtime__V1alpha2__StopPodRequest
{
  ProtobufCMessage base;
  char *pod_sandbox_id;
};
#define RUNTIME__V1ALPHA2__STOP_POD_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__stop_pod_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__StopPodResponse
{
  ProtobufCMessage base;
};
#define RUNTIME__V1ALPHA2__STOP_POD_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__stop_pod_response__descriptor) \
     }


struct  _Runtime__V1alpha2__ContainerConfig__LabelsEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__CONTAINER_CONFIG__LABELS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__container_config__labels_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__ContainerConfig__AnnotationsEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__CONTAINER_CONFIG__ANNOTATIONS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__container_config__annotations_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * Container messages
 */
struct  _Runtime__V1alpha2__ContainerConfig
{
  ProtobufCMessage base;
  Runtime__V1alpha2__ContainerMetadata *metadata;
  Runtime__V1alpha2__ImageSpec *image;
  size_t n_command;
  char **command;
  size_t n_args;
  char **args;
  char *working_dir;
  size_t n_envs;
  Runtime__V1alpha2__KeyValue **envs;
  size_t n_mounts;
  Runtime__V1alpha2__Mount **mounts;
  size_t n_labels;
  Runtime__V1alpha2__ContainerConfig__LabelsEntry **labels;
  size_t n_annotations;
  Runtime__V1alpha2__ContainerConfig__AnnotationsEntry **annotations;
};
#define RUNTIME__V1ALPHA2__CONTAINER_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__container_config__descriptor) \
    , NULL, NULL, 0,NULL, 0,NULL, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, 0,NULL, 0,NULL }


struct  _Runtime__V1alpha2__ContainerMetadata
{
  ProtobufCMessage base;
  char *name;
  uint32_t attempt;
};
#define RUNTIME__V1ALPHA2__CONTAINER_METADATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__container_metadata__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _Runtime__V1alpha2__ImageSpec
{
  ProtobufCMessage base;
  char *image;
};
#define RUNTIME__V1ALPHA2__IMAGE_SPEC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__image_spec__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__KeyValue
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__KEY_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__key_value__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__Mount
{
  ProtobufCMessage base;
  char *container_path;
  char *host_path;
  protobuf_c_boolean readonly;
};
#define RUNTIME__V1ALPHA2__MOUNT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__mount__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  _Runtime__V1alpha2__CreateContainerRequest
{
  ProtobufCMessage base;
  char *pod_sandbox_id;
  Runtime__V1alpha2__ContainerConfig *config;
  Runtime__V1alpha2__PodSandboxConfig *sandbox_config;
};
#define RUNTIME__V1ALPHA2__CREATE_CONTAINER_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__create_container_request__descriptor) \
    , (char *)protobuf_c_empty_string, NULL, NULL }


struct  _Runtime__V1alpha2__CreateContainerResponse
{
  ProtobufCMessage base;
  char *container_id;
};
#define RUNTIME__V1ALPHA2__CREATE_CONTAINER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__create_container_response__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__DeleteContainerRequest
{
  ProtobufCMessage base;
  char *container_id;
};
#define RUNTIME__V1ALPHA2__DELETE_CONTAINER_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__delete_container_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__DeleteContainerResponse
{
  ProtobufCMessage base;
};
#define RUNTIME__V1ALPHA2__DELETE_CONTAINER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__delete_container_response__descriptor) \
     }


struct  _Runtime__V1alpha2__ListContainersRequest
{
  ProtobufCMessage base;
  Runtime__V1alpha2__ContainerFilter *filter;
};
#define RUNTIME__V1ALPHA2__LIST_CONTAINERS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__list_containers_request__descriptor) \
    , NULL }


struct  _Runtime__V1alpha2__ContainerFilter__LabelSelectorEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__CONTAINER_FILTER__LABEL_SELECTOR_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__container_filter__label_selector_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__ContainerFilter
{
  ProtobufCMessage base;
  char *id;
  char *pod_sandbox_id;
  Runtime__V1alpha2__ContainerState state;
  size_t n_label_selector;
  Runtime__V1alpha2__ContainerFilter__LabelSelectorEntry **label_selector;
};
#define RUNTIME__V1ALPHA2__CONTAINER_FILTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__container_filter__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, RUNTIME__V1ALPHA2__CONTAINER_STATE__CONTAINER_UNKNOWN, 0,NULL }


struct  _Runtime__V1alpha2__ListContainersResponse
{
  ProtobufCMessage base;
  size_t n_containers;
  Runtime__V1alpha2__Container **containers;
};
#define RUNTIME__V1ALPHA2__LIST_CONTAINERS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__list_containers_response__descriptor) \
    , 0,NULL }


struct  _Runtime__V1alpha2__Container__LabelsEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__CONTAINER__LABELS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__container__labels_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__Container__AnnotationsEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define RUNTIME__V1ALPHA2__CONTAINER__ANNOTATIONS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__container__annotations_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__Container
{
  ProtobufCMessage base;
  char *id;
  char *pod_id;
  Runtime__V1alpha2__ContainerMetadata *metadata;
  Runtime__V1alpha2__ImageSpec *image;
  char *image_ref;
  Runtime__V1alpha2__ContainerState state;
  int64_t created_at;
  size_t n_labels;
  Runtime__V1alpha2__Container__LabelsEntry **labels;
  size_t n_annotations;
  Runtime__V1alpha2__Container__AnnotationsEntry **annotations;
};
#define RUNTIME__V1ALPHA2__CONTAINER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__container__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, NULL, NULL, (char *)protobuf_c_empty_string, RUNTIME__V1ALPHA2__CONTAINER_STATE__CONTAINER_UNKNOWN, 0, 0,NULL, 0,NULL }


struct  _Runtime__V1alpha2__StartContainerRequest
{
  ProtobufCMessage base;
  char *container_id;
};
#define RUNTIME__V1ALPHA2__START_CONTAINER_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__start_container_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Runtime__V1alpha2__StartContainerResponse
{
  ProtobufCMessage base;
};
#define RUNTIME__V1ALPHA2__START_CONTAINER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__start_container_response__descriptor) \
     }


struct  _Runtime__V1alpha2__StopContainerRequest
{
  ProtobufCMessage base;
  char *container_id;
  int64_t timeout;
};
#define RUNTIME__V1ALPHA2__STOP_CONTAINER_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__stop_container_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _Runtime__V1alpha2__StopContainerResponse
{
  ProtobufCMessage base;
};
#define RUNTIME__V1ALPHA2__STOP_CONTAINER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&runtime__v1alpha2__stop_container_response__descriptor) \
     }


/* Runtime__V1alpha2__DNSConfig methods */
void   runtime__v1alpha2__dnsconfig__init
                     (Runtime__V1alpha2__DNSConfig         *message);
size_t runtime__v1alpha2__dnsconfig__get_packed_size
                     (const Runtime__V1alpha2__DNSConfig   *message);
size_t runtime__v1alpha2__dnsconfig__pack
                     (const Runtime__V1alpha2__DNSConfig   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__dnsconfig__pack_to_buffer
                     (const Runtime__V1alpha2__DNSConfig   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__DNSConfig *
       runtime__v1alpha2__dnsconfig__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__dnsconfig__free_unpacked
                     (Runtime__V1alpha2__DNSConfig *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__PortMapping methods */
void   runtime__v1alpha2__port_mapping__init
                     (Runtime__V1alpha2__PortMapping         *message);
size_t runtime__v1alpha2__port_mapping__get_packed_size
                     (const Runtime__V1alpha2__PortMapping   *message);
size_t runtime__v1alpha2__port_mapping__pack
                     (const Runtime__V1alpha2__PortMapping   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__port_mapping__pack_to_buffer
                     (const Runtime__V1alpha2__PortMapping   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__PortMapping *
       runtime__v1alpha2__port_mapping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__port_mapping__free_unpacked
                     (Runtime__V1alpha2__PortMapping *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__LinuxPodSandboxConfig__SysctlsEntry methods */
void   runtime__v1alpha2__linux_pod_sandbox_config__sysctls_entry__init
                     (Runtime__V1alpha2__LinuxPodSandboxConfig__SysctlsEntry         *message);
/* Runtime__V1alpha2__LinuxPodSandboxConfig methods */
void   runtime__v1alpha2__linux_pod_sandbox_config__init
                     (Runtime__V1alpha2__LinuxPodSandboxConfig         *message);
size_t runtime__v1alpha2__linux_pod_sandbox_config__get_packed_size
                     (const Runtime__V1alpha2__LinuxPodSandboxConfig   *message);
size_t runtime__v1alpha2__linux_pod_sandbox_config__pack
                     (const Runtime__V1alpha2__LinuxPodSandboxConfig   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__linux_pod_sandbox_config__pack_to_buffer
                     (const Runtime__V1alpha2__LinuxPodSandboxConfig   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__LinuxPodSandboxConfig *
       runtime__v1alpha2__linux_pod_sandbox_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__linux_pod_sandbox_config__free_unpacked
                     (Runtime__V1alpha2__LinuxPodSandboxConfig *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__PodSandboxConfig__LabelsEntry methods */
void   runtime__v1alpha2__pod_sandbox_config__labels_entry__init
                     (Runtime__V1alpha2__PodSandboxConfig__LabelsEntry         *message);
/* Runtime__V1alpha2__PodSandboxConfig__AnnotationsEntry methods */
void   runtime__v1alpha2__pod_sandbox_config__annotations_entry__init
                     (Runtime__V1alpha2__PodSandboxConfig__AnnotationsEntry         *message);
/* Runtime__V1alpha2__PodSandboxConfig methods */
void   runtime__v1alpha2__pod_sandbox_config__init
                     (Runtime__V1alpha2__PodSandboxConfig         *message);
size_t runtime__v1alpha2__pod_sandbox_config__get_packed_size
                     (const Runtime__V1alpha2__PodSandboxConfig   *message);
size_t runtime__v1alpha2__pod_sandbox_config__pack
                     (const Runtime__V1alpha2__PodSandboxConfig   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__pod_sandbox_config__pack_to_buffer
                     (const Runtime__V1alpha2__PodSandboxConfig   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__PodSandboxConfig *
       runtime__v1alpha2__pod_sandbox_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__pod_sandbox_config__free_unpacked
                     (Runtime__V1alpha2__PodSandboxConfig *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__PodMetadata methods */
void   runtime__v1alpha2__pod_metadata__init
                     (Runtime__V1alpha2__PodMetadata         *message);
size_t runtime__v1alpha2__pod_metadata__get_packed_size
                     (const Runtime__V1alpha2__PodMetadata   *message);
size_t runtime__v1alpha2__pod_metadata__pack
                     (const Runtime__V1alpha2__PodMetadata   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__pod_metadata__pack_to_buffer
                     (const Runtime__V1alpha2__PodMetadata   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__PodMetadata *
       runtime__v1alpha2__pod_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__pod_metadata__free_unpacked
                     (Runtime__V1alpha2__PodMetadata *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__NetworkConfig methods */
void   runtime__v1alpha2__network_config__init
                     (Runtime__V1alpha2__NetworkConfig         *message);
size_t runtime__v1alpha2__network_config__get_packed_size
                     (const Runtime__V1alpha2__NetworkConfig   *message);
size_t runtime__v1alpha2__network_config__pack
                     (const Runtime__V1alpha2__NetworkConfig   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__network_config__pack_to_buffer
                     (const Runtime__V1alpha2__NetworkConfig   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__NetworkConfig *
       runtime__v1alpha2__network_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__network_config__free_unpacked
                     (Runtime__V1alpha2__NetworkConfig *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__LinuxConfig__SysctlsEntry methods */
void   runtime__v1alpha2__linux_config__sysctls_entry__init
                     (Runtime__V1alpha2__LinuxConfig__SysctlsEntry         *message);
/* Runtime__V1alpha2__LinuxConfig methods */
void   runtime__v1alpha2__linux_config__init
                     (Runtime__V1alpha2__LinuxConfig         *message);
size_t runtime__v1alpha2__linux_config__get_packed_size
                     (const Runtime__V1alpha2__LinuxConfig   *message);
size_t runtime__v1alpha2__linux_config__pack
                     (const Runtime__V1alpha2__LinuxConfig   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__linux_config__pack_to_buffer
                     (const Runtime__V1alpha2__LinuxConfig   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__LinuxConfig *
       runtime__v1alpha2__linux_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__linux_config__free_unpacked
                     (Runtime__V1alpha2__LinuxConfig *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__SecurityContext methods */
void   runtime__v1alpha2__security_context__init
                     (Runtime__V1alpha2__SecurityContext         *message);
size_t runtime__v1alpha2__security_context__get_packed_size
                     (const Runtime__V1alpha2__SecurityContext   *message);
size_t runtime__v1alpha2__security_context__pack
                     (const Runtime__V1alpha2__SecurityContext   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__security_context__pack_to_buffer
                     (const Runtime__V1alpha2__SecurityContext   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__SecurityContext *
       runtime__v1alpha2__security_context__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__security_context__free_unpacked
                     (Runtime__V1alpha2__SecurityContext *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__NamespaceOption methods */
void   runtime__v1alpha2__namespace_option__init
                     (Runtime__V1alpha2__NamespaceOption         *message);
size_t runtime__v1alpha2__namespace_option__get_packed_size
                     (const Runtime__V1alpha2__NamespaceOption   *message);
size_t runtime__v1alpha2__namespace_option__pack
                     (const Runtime__V1alpha2__NamespaceOption   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__namespace_option__pack_to_buffer
                     (const Runtime__V1alpha2__NamespaceOption   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__NamespaceOption *
       runtime__v1alpha2__namespace_option__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__namespace_option__free_unpacked
                     (Runtime__V1alpha2__NamespaceOption *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__SELinuxOption methods */
void   runtime__v1alpha2__selinux_option__init
                     (Runtime__V1alpha2__SELinuxOption         *message);
size_t runtime__v1alpha2__selinux_option__get_packed_size
                     (const Runtime__V1alpha2__SELinuxOption   *message);
size_t runtime__v1alpha2__selinux_option__pack
                     (const Runtime__V1alpha2__SELinuxOption   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__selinux_option__pack_to_buffer
                     (const Runtime__V1alpha2__SELinuxOption   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__SELinuxOption *
       runtime__v1alpha2__selinux_option__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__selinux_option__free_unpacked
                     (Runtime__V1alpha2__SELinuxOption *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__RunAsUserOption methods */
void   runtime__v1alpha2__run_as_user_option__init
                     (Runtime__V1alpha2__RunAsUserOption         *message);
size_t runtime__v1alpha2__run_as_user_option__get_packed_size
                     (const Runtime__V1alpha2__RunAsUserOption   *message);
size_t runtime__v1alpha2__run_as_user_option__pack
                     (const Runtime__V1alpha2__RunAsUserOption   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__run_as_user_option__pack_to_buffer
                     (const Runtime__V1alpha2__RunAsUserOption   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__RunAsUserOption *
       runtime__v1alpha2__run_as_user_option__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__run_as_user_option__free_unpacked
                     (Runtime__V1alpha2__RunAsUserOption *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__CreatePodRequest methods */
void   runtime__v1alpha2__create_pod_request__init
                     (Runtime__V1alpha2__CreatePodRequest         *message);
size_t runtime__v1alpha2__create_pod_request__get_packed_size
                     (const Runtime__V1alpha2__CreatePodRequest   *message);
size_t runtime__v1alpha2__create_pod_request__pack
                     (const Runtime__V1alpha2__CreatePodRequest   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__create_pod_request__pack_to_buffer
                     (const Runtime__V1alpha2__CreatePodRequest   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__CreatePodRequest *
       runtime__v1alpha2__create_pod_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__create_pod_request__free_unpacked
                     (Runtime__V1alpha2__CreatePodRequest *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__CreatePodResponse methods */
void   runtime__v1alpha2__create_pod_response__init
                     (Runtime__V1alpha2__CreatePodResponse         *message);
size_t runtime__v1alpha2__create_pod_response__get_packed_size
                     (const Runtime__V1alpha2__CreatePodResponse   *message);
size_t runtime__v1alpha2__create_pod_response__pack
                     (const Runtime__V1alpha2__CreatePodResponse   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__create_pod_response__pack_to_buffer
                     (const Runtime__V1alpha2__CreatePodResponse   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__CreatePodResponse *
       runtime__v1alpha2__create_pod_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__create_pod_response__free_unpacked
                     (Runtime__V1alpha2__CreatePodResponse *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__DeletePodRequest methods */
void   runtime__v1alpha2__delete_pod_request__init
                     (Runtime__V1alpha2__DeletePodRequest         *message);
size_t runtime__v1alpha2__delete_pod_request__get_packed_size
                     (const Runtime__V1alpha2__DeletePodRequest   *message);
size_t runtime__v1alpha2__delete_pod_request__pack
                     (const Runtime__V1alpha2__DeletePodRequest   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__delete_pod_request__pack_to_buffer
                     (const Runtime__V1alpha2__DeletePodRequest   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__DeletePodRequest *
       runtime__v1alpha2__delete_pod_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__delete_pod_request__free_unpacked
                     (Runtime__V1alpha2__DeletePodRequest *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__DeletePodResponse methods */
void   runtime__v1alpha2__delete_pod_response__init
                     (Runtime__V1alpha2__DeletePodResponse         *message);
size_t runtime__v1alpha2__delete_pod_response__get_packed_size
                     (const Runtime__V1alpha2__DeletePodResponse   *message);
size_t runtime__v1alpha2__delete_pod_response__pack
                     (const Runtime__V1alpha2__DeletePodResponse   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__delete_pod_response__pack_to_buffer
                     (const Runtime__V1alpha2__DeletePodResponse   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__DeletePodResponse *
       runtime__v1alpha2__delete_pod_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__delete_pod_response__free_unpacked
                     (Runtime__V1alpha2__DeletePodResponse *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__ListPodRequest methods */
void   runtime__v1alpha2__list_pod_request__init
                     (Runtime__V1alpha2__ListPodRequest         *message);
size_t runtime__v1alpha2__list_pod_request__get_packed_size
                     (const Runtime__V1alpha2__ListPodRequest   *message);
size_t runtime__v1alpha2__list_pod_request__pack
                     (const Runtime__V1alpha2__ListPodRequest   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__list_pod_request__pack_to_buffer
                     (const Runtime__V1alpha2__ListPodRequest   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__ListPodRequest *
       runtime__v1alpha2__list_pod_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__list_pod_request__free_unpacked
                     (Runtime__V1alpha2__ListPodRequest *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__PodFilter__LabelSelectorEntry methods */
void   runtime__v1alpha2__pod_filter__label_selector_entry__init
                     (Runtime__V1alpha2__PodFilter__LabelSelectorEntry         *message);
/* Runtime__V1alpha2__PodFilter methods */
void   runtime__v1alpha2__pod_filter__init
                     (Runtime__V1alpha2__PodFilter         *message);
size_t runtime__v1alpha2__pod_filter__get_packed_size
                     (const Runtime__V1alpha2__PodFilter   *message);
size_t runtime__v1alpha2__pod_filter__pack
                     (const Runtime__V1alpha2__PodFilter   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__pod_filter__pack_to_buffer
                     (const Runtime__V1alpha2__PodFilter   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__PodFilter *
       runtime__v1alpha2__pod_filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__pod_filter__free_unpacked
                     (Runtime__V1alpha2__PodFilter *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__ListPodResponse methods */
void   runtime__v1alpha2__list_pod_response__init
                     (Runtime__V1alpha2__ListPodResponse         *message);
size_t runtime__v1alpha2__list_pod_response__get_packed_size
                     (const Runtime__V1alpha2__ListPodResponse   *message);
size_t runtime__v1alpha2__list_pod_response__pack
                     (const Runtime__V1alpha2__ListPodResponse   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__list_pod_response__pack_to_buffer
                     (const Runtime__V1alpha2__ListPodResponse   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__ListPodResponse *
       runtime__v1alpha2__list_pod_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__list_pod_response__free_unpacked
                     (Runtime__V1alpha2__ListPodResponse *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__Pod__LabelsEntry methods */
void   runtime__v1alpha2__pod__labels_entry__init
                     (Runtime__V1alpha2__Pod__LabelsEntry         *message);
/* Runtime__V1alpha2__Pod__AnnotationsEntry methods */
void   runtime__v1alpha2__pod__annotations_entry__init
                     (Runtime__V1alpha2__Pod__AnnotationsEntry         *message);
/* Runtime__V1alpha2__Pod methods */
void   runtime__v1alpha2__pod__init
                     (Runtime__V1alpha2__Pod         *message);
size_t runtime__v1alpha2__pod__get_packed_size
                     (const Runtime__V1alpha2__Pod   *message);
size_t runtime__v1alpha2__pod__pack
                     (const Runtime__V1alpha2__Pod   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__pod__pack_to_buffer
                     (const Runtime__V1alpha2__Pod   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__Pod *
       runtime__v1alpha2__pod__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__pod__free_unpacked
                     (Runtime__V1alpha2__Pod *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__StartPodRequest methods */
void   runtime__v1alpha2__start_pod_request__init
                     (Runtime__V1alpha2__StartPodRequest         *message);
size_t runtime__v1alpha2__start_pod_request__get_packed_size
                     (const Runtime__V1alpha2__StartPodRequest   *message);
size_t runtime__v1alpha2__start_pod_request__pack
                     (const Runtime__V1alpha2__StartPodRequest   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__start_pod_request__pack_to_buffer
                     (const Runtime__V1alpha2__StartPodRequest   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__StartPodRequest *
       runtime__v1alpha2__start_pod_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__start_pod_request__free_unpacked
                     (Runtime__V1alpha2__StartPodRequest *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__StartPodResponse methods */
void   runtime__v1alpha2__start_pod_response__init
                     (Runtime__V1alpha2__StartPodResponse         *message);
size_t runtime__v1alpha2__start_pod_response__get_packed_size
                     (const Runtime__V1alpha2__StartPodResponse   *message);
size_t runtime__v1alpha2__start_pod_response__pack
                     (const Runtime__V1alpha2__StartPodResponse   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__start_pod_response__pack_to_buffer
                     (const Runtime__V1alpha2__StartPodResponse   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__StartPodResponse *
       runtime__v1alpha2__start_pod_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__start_pod_response__free_unpacked
                     (Runtime__V1alpha2__StartPodResponse *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__StopPodRequest methods */
void   runtime__v1alpha2__stop_pod_request__init
                     (Runtime__V1alpha2__StopPodRequest         *message);
size_t runtime__v1alpha2__stop_pod_request__get_packed_size
                     (const Runtime__V1alpha2__StopPodRequest   *message);
size_t runtime__v1alpha2__stop_pod_request__pack
                     (const Runtime__V1alpha2__StopPodRequest   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__stop_pod_request__pack_to_buffer
                     (const Runtime__V1alpha2__StopPodRequest   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__StopPodRequest *
       runtime__v1alpha2__stop_pod_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__stop_pod_request__free_unpacked
                     (Runtime__V1alpha2__StopPodRequest *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__StopPodResponse methods */
void   runtime__v1alpha2__stop_pod_response__init
                     (Runtime__V1alpha2__StopPodResponse         *message);
size_t runtime__v1alpha2__stop_pod_response__get_packed_size
                     (const Runtime__V1alpha2__StopPodResponse   *message);
size_t runtime__v1alpha2__stop_pod_response__pack
                     (const Runtime__V1alpha2__StopPodResponse   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__stop_pod_response__pack_to_buffer
                     (const Runtime__V1alpha2__StopPodResponse   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__StopPodResponse *
       runtime__v1alpha2__stop_pod_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__stop_pod_response__free_unpacked
                     (Runtime__V1alpha2__StopPodResponse *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__ContainerConfig__LabelsEntry methods */
void   runtime__v1alpha2__container_config__labels_entry__init
                     (Runtime__V1alpha2__ContainerConfig__LabelsEntry         *message);
/* Runtime__V1alpha2__ContainerConfig__AnnotationsEntry methods */
void   runtime__v1alpha2__container_config__annotations_entry__init
                     (Runtime__V1alpha2__ContainerConfig__AnnotationsEntry         *message);
/* Runtime__V1alpha2__ContainerConfig methods */
void   runtime__v1alpha2__container_config__init
                     (Runtime__V1alpha2__ContainerConfig         *message);
size_t runtime__v1alpha2__container_config__get_packed_size
                     (const Runtime__V1alpha2__ContainerConfig   *message);
size_t runtime__v1alpha2__container_config__pack
                     (const Runtime__V1alpha2__ContainerConfig   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__container_config__pack_to_buffer
                     (const Runtime__V1alpha2__ContainerConfig   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__ContainerConfig *
       runtime__v1alpha2__container_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__container_config__free_unpacked
                     (Runtime__V1alpha2__ContainerConfig *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__ContainerMetadata methods */
void   runtime__v1alpha2__container_metadata__init
                     (Runtime__V1alpha2__ContainerMetadata         *message);
size_t runtime__v1alpha2__container_metadata__get_packed_size
                     (const Runtime__V1alpha2__ContainerMetadata   *message);
size_t runtime__v1alpha2__container_metadata__pack
                     (const Runtime__V1alpha2__ContainerMetadata   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__container_metadata__pack_to_buffer
                     (const Runtime__V1alpha2__ContainerMetadata   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__ContainerMetadata *
       runtime__v1alpha2__container_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__container_metadata__free_unpacked
                     (Runtime__V1alpha2__ContainerMetadata *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__ImageSpec methods */
void   runtime__v1alpha2__image_spec__init
                     (Runtime__V1alpha2__ImageSpec         *message);
size_t runtime__v1alpha2__image_spec__get_packed_size
                     (const Runtime__V1alpha2__ImageSpec   *message);
size_t runtime__v1alpha2__image_spec__pack
                     (const Runtime__V1alpha2__ImageSpec   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__image_spec__pack_to_buffer
                     (const Runtime__V1alpha2__ImageSpec   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__ImageSpec *
       runtime__v1alpha2__image_spec__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__image_spec__free_unpacked
                     (Runtime__V1alpha2__ImageSpec *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__KeyValue methods */
void   runtime__v1alpha2__key_value__init
                     (Runtime__V1alpha2__KeyValue         *message);
size_t runtime__v1alpha2__key_value__get_packed_size
                     (const Runtime__V1alpha2__KeyValue   *message);
size_t runtime__v1alpha2__key_value__pack
                     (const Runtime__V1alpha2__KeyValue   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__key_value__pack_to_buffer
                     (const Runtime__V1alpha2__KeyValue   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__KeyValue *
       runtime__v1alpha2__key_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__key_value__free_unpacked
                     (Runtime__V1alpha2__KeyValue *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__Mount methods */
void   runtime__v1alpha2__mount__init
                     (Runtime__V1alpha2__Mount         *message);
size_t runtime__v1alpha2__mount__get_packed_size
                     (const Runtime__V1alpha2__Mount   *message);
size_t runtime__v1alpha2__mount__pack
                     (const Runtime__V1alpha2__Mount   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__mount__pack_to_buffer
                     (const Runtime__V1alpha2__Mount   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__Mount *
       runtime__v1alpha2__mount__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__mount__free_unpacked
                     (Runtime__V1alpha2__Mount *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__CreateContainerRequest methods */
void   runtime__v1alpha2__create_container_request__init
                     (Runtime__V1alpha2__CreateContainerRequest         *message);
size_t runtime__v1alpha2__create_container_request__get_packed_size
                     (const Runtime__V1alpha2__CreateContainerRequest   *message);
size_t runtime__v1alpha2__create_container_request__pack
                     (const Runtime__V1alpha2__CreateContainerRequest   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__create_container_request__pack_to_buffer
                     (const Runtime__V1alpha2__CreateContainerRequest   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__CreateContainerRequest *
       runtime__v1alpha2__create_container_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__create_container_request__free_unpacked
                     (Runtime__V1alpha2__CreateContainerRequest *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__CreateContainerResponse methods */
void   runtime__v1alpha2__create_container_response__init
                     (Runtime__V1alpha2__CreateContainerResponse         *message);
size_t runtime__v1alpha2__create_container_response__get_packed_size
                     (const Runtime__V1alpha2__CreateContainerResponse   *message);
size_t runtime__v1alpha2__create_container_response__pack
                     (const Runtime__V1alpha2__CreateContainerResponse   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__create_container_response__pack_to_buffer
                     (const Runtime__V1alpha2__CreateContainerResponse   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__CreateContainerResponse *
       runtime__v1alpha2__create_container_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__create_container_response__free_unpacked
                     (Runtime__V1alpha2__CreateContainerResponse *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__DeleteContainerRequest methods */
void   runtime__v1alpha2__delete_container_request__init
                     (Runtime__V1alpha2__DeleteContainerRequest         *message);
size_t runtime__v1alpha2__delete_container_request__get_packed_size
                     (const Runtime__V1alpha2__DeleteContainerRequest   *message);
size_t runtime__v1alpha2__delete_container_request__pack
                     (const Runtime__V1alpha2__DeleteContainerRequest   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__delete_container_request__pack_to_buffer
                     (const Runtime__V1alpha2__DeleteContainerRequest   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__DeleteContainerRequest *
       runtime__v1alpha2__delete_container_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__delete_container_request__free_unpacked
                     (Runtime__V1alpha2__DeleteContainerRequest *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__DeleteContainerResponse methods */
void   runtime__v1alpha2__delete_container_response__init
                     (Runtime__V1alpha2__DeleteContainerResponse         *message);
size_t runtime__v1alpha2__delete_container_response__get_packed_size
                     (const Runtime__V1alpha2__DeleteContainerResponse   *message);
size_t runtime__v1alpha2__delete_container_response__pack
                     (const Runtime__V1alpha2__DeleteContainerResponse   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__delete_container_response__pack_to_buffer
                     (const Runtime__V1alpha2__DeleteContainerResponse   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__DeleteContainerResponse *
       runtime__v1alpha2__delete_container_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__delete_container_response__free_unpacked
                     (Runtime__V1alpha2__DeleteContainerResponse *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__ListContainersRequest methods */
void   runtime__v1alpha2__list_containers_request__init
                     (Runtime__V1alpha2__ListContainersRequest         *message);
size_t runtime__v1alpha2__list_containers_request__get_packed_size
                     (const Runtime__V1alpha2__ListContainersRequest   *message);
size_t runtime__v1alpha2__list_containers_request__pack
                     (const Runtime__V1alpha2__ListContainersRequest   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__list_containers_request__pack_to_buffer
                     (const Runtime__V1alpha2__ListContainersRequest   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__ListContainersRequest *
       runtime__v1alpha2__list_containers_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__list_containers_request__free_unpacked
                     (Runtime__V1alpha2__ListContainersRequest *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__ContainerFilter__LabelSelectorEntry methods */
void   runtime__v1alpha2__container_filter__label_selector_entry__init
                     (Runtime__V1alpha2__ContainerFilter__LabelSelectorEntry         *message);
/* Runtime__V1alpha2__ContainerFilter methods */
void   runtime__v1alpha2__container_filter__init
                     (Runtime__V1alpha2__ContainerFilter         *message);
size_t runtime__v1alpha2__container_filter__get_packed_size
                     (const Runtime__V1alpha2__ContainerFilter   *message);
size_t runtime__v1alpha2__container_filter__pack
                     (const Runtime__V1alpha2__ContainerFilter   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__container_filter__pack_to_buffer
                     (const Runtime__V1alpha2__ContainerFilter   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__ContainerFilter *
       runtime__v1alpha2__container_filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__container_filter__free_unpacked
                     (Runtime__V1alpha2__ContainerFilter *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__ListContainersResponse methods */
void   runtime__v1alpha2__list_containers_response__init
                     (Runtime__V1alpha2__ListContainersResponse         *message);
size_t runtime__v1alpha2__list_containers_response__get_packed_size
                     (const Runtime__V1alpha2__ListContainersResponse   *message);
size_t runtime__v1alpha2__list_containers_response__pack
                     (const Runtime__V1alpha2__ListContainersResponse   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__list_containers_response__pack_to_buffer
                     (const Runtime__V1alpha2__ListContainersResponse   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__ListContainersResponse *
       runtime__v1alpha2__list_containers_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__list_containers_response__free_unpacked
                     (Runtime__V1alpha2__ListContainersResponse *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__Container__LabelsEntry methods */
void   runtime__v1alpha2__container__labels_entry__init
                     (Runtime__V1alpha2__Container__LabelsEntry         *message);
/* Runtime__V1alpha2__Container__AnnotationsEntry methods */
void   runtime__v1alpha2__container__annotations_entry__init
                     (Runtime__V1alpha2__Container__AnnotationsEntry         *message);
/* Runtime__V1alpha2__Container methods */
void   runtime__v1alpha2__container__init
                     (Runtime__V1alpha2__Container         *message);
size_t runtime__v1alpha2__container__get_packed_size
                     (const Runtime__V1alpha2__Container   *message);
size_t runtime__v1alpha2__container__pack
                     (const Runtime__V1alpha2__Container   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__container__pack_to_buffer
                     (const Runtime__V1alpha2__Container   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__Container *
       runtime__v1alpha2__container__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__container__free_unpacked
                     (Runtime__V1alpha2__Container *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__StartContainerRequest methods */
void   runtime__v1alpha2__start_container_request__init
                     (Runtime__V1alpha2__StartContainerRequest         *message);
size_t runtime__v1alpha2__start_container_request__get_packed_size
                     (const Runtime__V1alpha2__StartContainerRequest   *message);
size_t runtime__v1alpha2__start_container_request__pack
                     (const Runtime__V1alpha2__StartContainerRequest   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__start_container_request__pack_to_buffer
                     (const Runtime__V1alpha2__StartContainerRequest   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__StartContainerRequest *
       runtime__v1alpha2__start_container_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__start_container_request__free_unpacked
                     (Runtime__V1alpha2__StartContainerRequest *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__StartContainerResponse methods */
void   runtime__v1alpha2__start_container_response__init
                     (Runtime__V1alpha2__StartContainerResponse         *message);
size_t runtime__v1alpha2__start_container_response__get_packed_size
                     (const Runtime__V1alpha2__StartContainerResponse   *message);
size_t runtime__v1alpha2__start_container_response__pack
                     (const Runtime__V1alpha2__StartContainerResponse   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__start_container_response__pack_to_buffer
                     (const Runtime__V1alpha2__StartContainerResponse   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__StartContainerResponse *
       runtime__v1alpha2__start_container_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__start_container_response__free_unpacked
                     (Runtime__V1alpha2__StartContainerResponse *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__StopContainerRequest methods */
void   runtime__v1alpha2__stop_container_request__init
                     (Runtime__V1alpha2__StopContainerRequest         *message);
size_t runtime__v1alpha2__stop_container_request__get_packed_size
                     (const Runtime__V1alpha2__StopContainerRequest   *message);
size_t runtime__v1alpha2__stop_container_request__pack
                     (const Runtime__V1alpha2__StopContainerRequest   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__stop_container_request__pack_to_buffer
                     (const Runtime__V1alpha2__StopContainerRequest   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__StopContainerRequest *
       runtime__v1alpha2__stop_container_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__stop_container_request__free_unpacked
                     (Runtime__V1alpha2__StopContainerRequest *message,
                      ProtobufCAllocator *allocator);
/* Runtime__V1alpha2__StopContainerResponse methods */
void   runtime__v1alpha2__stop_container_response__init
                     (Runtime__V1alpha2__StopContainerResponse         *message);
size_t runtime__v1alpha2__stop_container_response__get_packed_size
                     (const Runtime__V1alpha2__StopContainerResponse   *message);
size_t runtime__v1alpha2__stop_container_response__pack
                     (const Runtime__V1alpha2__StopContainerResponse   *message,
                      uint8_t             *out);
size_t runtime__v1alpha2__stop_container_response__pack_to_buffer
                     (const Runtime__V1alpha2__StopContainerResponse   *message,
                      ProtobufCBuffer     *buffer);
Runtime__V1alpha2__StopContainerResponse *
       runtime__v1alpha2__stop_container_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   runtime__v1alpha2__stop_container_response__free_unpacked
                     (Runtime__V1alpha2__StopContainerResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Runtime__V1alpha2__DNSConfig_Closure)
                 (const Runtime__V1alpha2__DNSConfig *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__PortMapping_Closure)
                 (const Runtime__V1alpha2__PortMapping *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__LinuxPodSandboxConfig__SysctlsEntry_Closure)
                 (const Runtime__V1alpha2__LinuxPodSandboxConfig__SysctlsEntry *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__LinuxPodSandboxConfig_Closure)
                 (const Runtime__V1alpha2__LinuxPodSandboxConfig *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__PodSandboxConfig__LabelsEntry_Closure)
                 (const Runtime__V1alpha2__PodSandboxConfig__LabelsEntry *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__PodSandboxConfig__AnnotationsEntry_Closure)
                 (const Runtime__V1alpha2__PodSandboxConfig__AnnotationsEntry *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__PodSandboxConfig_Closure)
                 (const Runtime__V1alpha2__PodSandboxConfig *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__PodMetadata_Closure)
                 (const Runtime__V1alpha2__PodMetadata *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__NetworkConfig_Closure)
                 (const Runtime__V1alpha2__NetworkConfig *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__LinuxConfig__SysctlsEntry_Closure)
                 (const Runtime__V1alpha2__LinuxConfig__SysctlsEntry *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__LinuxConfig_Closure)
                 (const Runtime__V1alpha2__LinuxConfig *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__SecurityContext_Closure)
                 (const Runtime__V1alpha2__SecurityContext *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__NamespaceOption_Closure)
                 (const Runtime__V1alpha2__NamespaceOption *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__SELinuxOption_Closure)
                 (const Runtime__V1alpha2__SELinuxOption *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__RunAsUserOption_Closure)
                 (const Runtime__V1alpha2__RunAsUserOption *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__CreatePodRequest_Closure)
                 (const Runtime__V1alpha2__CreatePodRequest *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__CreatePodResponse_Closure)
                 (const Runtime__V1alpha2__CreatePodResponse *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__DeletePodRequest_Closure)
                 (const Runtime__V1alpha2__DeletePodRequest *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__DeletePodResponse_Closure)
                 (const Runtime__V1alpha2__DeletePodResponse *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__ListPodRequest_Closure)
                 (const Runtime__V1alpha2__ListPodRequest *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__PodFilter__LabelSelectorEntry_Closure)
                 (const Runtime__V1alpha2__PodFilter__LabelSelectorEntry *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__PodFilter_Closure)
                 (const Runtime__V1alpha2__PodFilter *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__ListPodResponse_Closure)
                 (const Runtime__V1alpha2__ListPodResponse *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__Pod__LabelsEntry_Closure)
                 (const Runtime__V1alpha2__Pod__LabelsEntry *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__Pod__AnnotationsEntry_Closure)
                 (const Runtime__V1alpha2__Pod__AnnotationsEntry *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__Pod_Closure)
                 (const Runtime__V1alpha2__Pod *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__StartPodRequest_Closure)
                 (const Runtime__V1alpha2__StartPodRequest *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__StartPodResponse_Closure)
                 (const Runtime__V1alpha2__StartPodResponse *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__StopPodRequest_Closure)
                 (const Runtime__V1alpha2__StopPodRequest *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__StopPodResponse_Closure)
                 (const Runtime__V1alpha2__StopPodResponse *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__ContainerConfig__LabelsEntry_Closure)
                 (const Runtime__V1alpha2__ContainerConfig__LabelsEntry *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__ContainerConfig__AnnotationsEntry_Closure)
                 (const Runtime__V1alpha2__ContainerConfig__AnnotationsEntry *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__ContainerConfig_Closure)
                 (const Runtime__V1alpha2__ContainerConfig *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__ContainerMetadata_Closure)
                 (const Runtime__V1alpha2__ContainerMetadata *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__ImageSpec_Closure)
                 (const Runtime__V1alpha2__ImageSpec *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__KeyValue_Closure)
                 (const Runtime__V1alpha2__KeyValue *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__Mount_Closure)
                 (const Runtime__V1alpha2__Mount *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__CreateContainerRequest_Closure)
                 (const Runtime__V1alpha2__CreateContainerRequest *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__CreateContainerResponse_Closure)
                 (const Runtime__V1alpha2__CreateContainerResponse *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__DeleteContainerRequest_Closure)
                 (const Runtime__V1alpha2__DeleteContainerRequest *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__DeleteContainerResponse_Closure)
                 (const Runtime__V1alpha2__DeleteContainerResponse *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__ListContainersRequest_Closure)
                 (const Runtime__V1alpha2__ListContainersRequest *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__ContainerFilter__LabelSelectorEntry_Closure)
                 (const Runtime__V1alpha2__ContainerFilter__LabelSelectorEntry *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__ContainerFilter_Closure)
                 (const Runtime__V1alpha2__ContainerFilter *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__ListContainersResponse_Closure)
                 (const Runtime__V1alpha2__ListContainersResponse *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__Container__LabelsEntry_Closure)
                 (const Runtime__V1alpha2__Container__LabelsEntry *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__Container__AnnotationsEntry_Closure)
                 (const Runtime__V1alpha2__Container__AnnotationsEntry *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__Container_Closure)
                 (const Runtime__V1alpha2__Container *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__StartContainerRequest_Closure)
                 (const Runtime__V1alpha2__StartContainerRequest *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__StartContainerResponse_Closure)
                 (const Runtime__V1alpha2__StartContainerResponse *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__StopContainerRequest_Closure)
                 (const Runtime__V1alpha2__StopContainerRequest *message,
                  void *closure_data);
typedef void (*Runtime__V1alpha2__StopContainerResponse_Closure)
                 (const Runtime__V1alpha2__StopContainerResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct _Runtime__V1alpha2__RuntimeService_Service Runtime__V1alpha2__RuntimeService_Service;
struct _Runtime__V1alpha2__RuntimeService_Service
{
  ProtobufCService base;
  void (*create_pod)(Runtime__V1alpha2__RuntimeService_Service *service,
                     const Runtime__V1alpha2__CreatePodRequest *input,
                     Runtime__V1alpha2__CreatePodResponse_Closure closure,
                     void *closure_data);
  void (*delete_pod)(Runtime__V1alpha2__RuntimeService_Service *service,
                     const Runtime__V1alpha2__DeletePodRequest *input,
                     Runtime__V1alpha2__DeletePodResponse_Closure closure,
                     void *closure_data);
  void (*list_pods)(Runtime__V1alpha2__RuntimeService_Service *service,
                    const Runtime__V1alpha2__ListPodRequest *input,
                    Runtime__V1alpha2__ListPodResponse_Closure closure,
                    void *closure_data);
  void (*start_pod)(Runtime__V1alpha2__RuntimeService_Service *service,
                    const Runtime__V1alpha2__StartPodRequest *input,
                    Runtime__V1alpha2__StartPodResponse_Closure closure,
                    void *closure_data);
  void (*stop_pod)(Runtime__V1alpha2__RuntimeService_Service *service,
                   const Runtime__V1alpha2__StopPodRequest *input,
                   Runtime__V1alpha2__StopPodResponse_Closure closure,
                   void *closure_data);
  void (*create_container)(Runtime__V1alpha2__RuntimeService_Service *service,
                           const Runtime__V1alpha2__CreateContainerRequest *input,
                           Runtime__V1alpha2__CreateContainerResponse_Closure closure,
                           void *closure_data);
  void (*delete_container)(Runtime__V1alpha2__RuntimeService_Service *service,
                           const Runtime__V1alpha2__DeleteContainerRequest *input,
                           Runtime__V1alpha2__DeleteContainerResponse_Closure closure,
                           void *closure_data);
  void (*list_containers)(Runtime__V1alpha2__RuntimeService_Service *service,
                          const Runtime__V1alpha2__ListContainersRequest *input,
                          Runtime__V1alpha2__ListContainersResponse_Closure closure,
                          void *closure_data);
  void (*start_container)(Runtime__V1alpha2__RuntimeService_Service *service,
                          const Runtime__V1alpha2__StartContainerRequest *input,
                          Runtime__V1alpha2__StartContainerResponse_Closure closure,
                          void *closure_data);
  void (*stop_container)(Runtime__V1alpha2__RuntimeService_Service *service,
                         const Runtime__V1alpha2__StopContainerRequest *input,
                         Runtime__V1alpha2__StopContainerResponse_Closure closure,
                         void *closure_data);
};
typedef void (*Runtime__V1alpha2__RuntimeService_ServiceDestroy)(Runtime__V1alpha2__RuntimeService_Service *);
void runtime__v1alpha2__runtime_service__init (Runtime__V1alpha2__RuntimeService_Service *service,
                                               Runtime__V1alpha2__RuntimeService_ServiceDestroy destroy);
#define RUNTIME__V1ALPHA2__RUNTIME_SERVICE__BASE_INIT \
    { &runtime__v1alpha2__runtime_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define RUNTIME__V1ALPHA2__RUNTIME_SERVICE__INIT(function_prefix__) \
    { RUNTIME__V1ALPHA2__RUNTIME_SERVICE__BASE_INIT,\
      function_prefix__ ## create_pod,\
      function_prefix__ ## delete_pod,\
      function_prefix__ ## list_pods,\
      function_prefix__ ## start_pod,\
      function_prefix__ ## stop_pod,\
      function_prefix__ ## create_container,\
      function_prefix__ ## delete_container,\
      function_prefix__ ## list_containers,\
      function_prefix__ ## start_container,\
      function_prefix__ ## stop_container  }
void runtime__v1alpha2__runtime_service__create_pod(ProtobufCService *service,
                                                    const Runtime__V1alpha2__CreatePodRequest *input,
                                                    Runtime__V1alpha2__CreatePodResponse_Closure closure,
                                                    void *closure_data);
void runtime__v1alpha2__runtime_service__delete_pod(ProtobufCService *service,
                                                    const Runtime__V1alpha2__DeletePodRequest *input,
                                                    Runtime__V1alpha2__DeletePodResponse_Closure closure,
                                                    void *closure_data);
void runtime__v1alpha2__runtime_service__list_pods(ProtobufCService *service,
                                                   const Runtime__V1alpha2__ListPodRequest *input,
                                                   Runtime__V1alpha2__ListPodResponse_Closure closure,
                                                   void *closure_data);
void runtime__v1alpha2__runtime_service__start_pod(ProtobufCService *service,
                                                   const Runtime__V1alpha2__StartPodRequest *input,
                                                   Runtime__V1alpha2__StartPodResponse_Closure closure,
                                                   void *closure_data);
void runtime__v1alpha2__runtime_service__stop_pod(ProtobufCService *service,
                                                  const Runtime__V1alpha2__StopPodRequest *input,
                                                  Runtime__V1alpha2__StopPodResponse_Closure closure,
                                                  void *closure_data);
void runtime__v1alpha2__runtime_service__create_container(ProtobufCService *service,
                                                          const Runtime__V1alpha2__CreateContainerRequest *input,
                                                          Runtime__V1alpha2__CreateContainerResponse_Closure closure,
                                                          void *closure_data);
void runtime__v1alpha2__runtime_service__delete_container(ProtobufCService *service,
                                                          const Runtime__V1alpha2__DeleteContainerRequest *input,
                                                          Runtime__V1alpha2__DeleteContainerResponse_Closure closure,
                                                          void *closure_data);
void runtime__v1alpha2__runtime_service__list_containers(ProtobufCService *service,
                                                         const Runtime__V1alpha2__ListContainersRequest *input,
                                                         Runtime__V1alpha2__ListContainersResponse_Closure closure,
                                                         void *closure_data);
void runtime__v1alpha2__runtime_service__start_container(ProtobufCService *service,
                                                         const Runtime__V1alpha2__StartContainerRequest *input,
                                                         Runtime__V1alpha2__StartContainerResponse_Closure closure,
                                                         void *closure_data);
void runtime__v1alpha2__runtime_service__stop_container(ProtobufCService *service,
                                                        const Runtime__V1alpha2__StopContainerRequest *input,
                                                        Runtime__V1alpha2__StopContainerResponse_Closure closure,
                                                        void *closure_data);

/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    runtime__v1alpha2__pod_state__descriptor;
extern const ProtobufCEnumDescriptor    runtime__v1alpha2__container_state__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__dnsconfig__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__port_mapping__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__linux_pod_sandbox_config__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__linux_pod_sandbox_config__sysctls_entry__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__pod_sandbox_config__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__pod_sandbox_config__labels_entry__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__pod_sandbox_config__annotations_entry__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__pod_metadata__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__network_config__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__linux_config__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__linux_config__sysctls_entry__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__security_context__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__namespace_option__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__selinux_option__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__run_as_user_option__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__create_pod_request__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__create_pod_response__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__delete_pod_request__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__delete_pod_response__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__list_pod_request__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__pod_filter__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__pod_filter__label_selector_entry__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__list_pod_response__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__pod__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__pod__labels_entry__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__pod__annotations_entry__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__start_pod_request__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__start_pod_response__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__stop_pod_request__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__stop_pod_response__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__container_config__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__container_config__labels_entry__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__container_config__annotations_entry__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__container_metadata__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__image_spec__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__key_value__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__mount__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__create_container_request__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__create_container_response__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__delete_container_request__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__delete_container_response__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__list_containers_request__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__container_filter__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__container_filter__label_selector_entry__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__list_containers_response__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__container__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__container__labels_entry__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__container__annotations_entry__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__start_container_request__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__start_container_response__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__stop_container_request__descriptor;
extern const ProtobufCMessageDescriptor runtime__v1alpha2__stop_container_response__descriptor;
extern const ProtobufCServiceDescriptor runtime__v1alpha2__runtime_service__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_runtime_5fservice_2eproto__INCLUDED */
