#!/bin/bash
# Setup GitHub Actions runner permissions on Proxmox server
# This script must be run as root

set -euo pipefail

RUNNER_USER="${RUNNER_USER:-github-runner}"
SUDOERS_FILE="/etc/sudoers.d/${RUNNER_USER}"

echo "=== GitHub Actions Runner Permission Setup ==="
echo "Runner user: $RUNNER_USER"
echo "Sudoers file: $SUDOERS_FILE"
echo "Note: This configuration applies to all runner services using the $RUNNER_USER user"
echo

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "ERROR: This script must be run as root" 
   echo "Usage: sudo $0"
   exit 1
fi

# Check if runner user exists
if ! id "$RUNNER_USER" >/dev/null 2>&1; then
    echo "ERROR: User '$RUNNER_USER' does not exist"
    echo "Please create the user first or set RUNNER_USER environment variable"
    exit 1
fi

echo "✓ User '$RUNNER_USER' exists"

# Backup existing sudoers file if present
if [[ -f "$SUDOERS_FILE" ]]; then
    BACKUP="${SUDOERS_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    echo "Backing up existing sudoers file to: $BACKUP"
    cp "$SUDOERS_FILE" "$BACKUP"
fi

# Create sudoers configuration
echo "Creating sudoers configuration..."
cat > "$SUDOERS_FILE" << 'EOF'
# GitHub Actions runner permissions
# Generated by setup_runner_permissions.sh

# Allow package management (apt-get)
github-runner ALL=(root) NOPASSWD: /usr/bin/apt-get update
github-runner ALL=(root) NOPASSWD: /usr/bin/apt-get install *
github-runner ALL=(root) NOPASSWD: /usr/bin/apt-get upgrade *
github-runner ALL=(root) NOPASSWD: /usr/bin/apt-get dist-upgrade *
github-runner ALL=(root) NOPASSWD: /usr/bin/apt-get autoremove *
github-runner ALL=(root) NOPASSWD: /usr/bin/dpkg *

# Allow Proxmox container management (pct)
github-runner ALL=(root) NOPASSWD: /usr/sbin/pct

# Allow Proxmox API access (pvesh)
github-runner ALL=(root) NOPASSWD: /usr/bin/pvesh

# Allow Proxmox storage management (pvesm)
github-runner ALL=(root) NOPASSWD: /usr/sbin/pvesm

# Allow systemd service management
github-runner ALL=(root) NOPASSWD: /usr/bin/systemctl enable *
github-runner ALL=(root) NOPASSWD: /usr/bin/systemctl start *
github-runner ALL=(root) NOPASSWD: /usr/bin/systemctl stop *
github-runner ALL=(root) NOPASSWD: /usr/bin/systemctl restart *
github-runner ALL=(root) NOPASSWD: /usr/bin/systemctl status *
github-runner ALL=(root) NOPASSWD: /usr/bin/systemctl daemon-reload

# Allow file operations for releases
github-runner ALL=(root) NOPASSWD: /usr/bin/mv * /usr/local/bin/*
github-runner ALL=(root) NOPASSWD: /usr/bin/cp * /usr/local/bin/*
github-runner ALL=(root) NOPASSWD: /usr/bin/chmod * /usr/local/bin/*

# Preserve environment variables for LXC operations
Defaults:github-runner env_keep += "LXC_MEMFD_REXEC"
Defaults:github-runner env_keep += "PATH"

# Disable requiretty for non-interactive sudo
Defaults:github-runner !requiretty
EOF

# Set correct permissions
chmod 0440 "$SUDOERS_FILE"
echo "✓ Created sudoers file with permissions 0440"

# Validate sudoers syntax
echo "Validating sudoers syntax..."
if visudo -c -f "$SUDOERS_FILE"; then
    echo "✓ Sudoers syntax is valid"
else
    echo "ERROR: Invalid sudoers syntax"
    echo "Restoring backup if available..."
    if [[ -f "$BACKUP" ]]; then
        mv "$BACKUP" "$SUDOERS_FILE"
        echo "Backup restored"
    else
        rm -f "$SUDOERS_FILE"
        echo "Invalid file removed"
    fi
    exit 1
fi

# Test permissions
echo
echo "=== Testing Permissions ==="

test_command() {
    local cmd="$1"
    local desc="$2"
    echo -n "Testing $desc... "
    if sudo -u "$RUNNER_USER" sudo -n $cmd >/dev/null 2>&1; then
        echo "✓"
        return 0
    else
        echo "✗ FAILED"
        return 1
    fi
}

FAILED=0

test_command "pct version" "pct" || FAILED=1
test_command "pvesh get /cluster/nextid" "pvesh" || FAILED=1
test_command "pvesm status" "pvesm" || FAILED=1
test_command "apt-get update --dry-run" "apt-get" || FAILED=1

if [[ $FAILED -eq 0 ]]; then
    echo
    echo "=== Setup Complete ==="
    echo "✓ All permissions configured successfully"
    echo "✓ Runner user '$RUNNER_USER' can now execute required commands"
else
    echo
    echo "=== Setup Complete with Warnings ==="
    echo "⚠ Some permission tests failed"
    echo "Please verify the configuration manually"
fi

echo
echo "Next steps:"
echo "1. Verify runner services: systemctl status actions.runner.*"
echo "2. For multi-runner setup, see docs/SELF_HOSTED_RUNNER_SETUP.md"
echo "3. Test workflow execution on GitHub Actions"
echo "4. Monitor logs: journalctl -u actions.runner.* -f"
echo

exit 0
