/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/oci_runtime.proto */

#ifndef PROTOBUF_C_proto_2foci_5fruntime_2eproto__INCLUDED
#define PROTOBUF_C_proto_2foci_5fruntime_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _OciRuntime__CreateContainerRequest OciRuntime__CreateContainerRequest;
typedef struct _OciRuntime__CreateContainerResponse OciRuntime__CreateContainerResponse;
typedef struct _OciRuntime__StartContainerRequest OciRuntime__StartContainerRequest;
typedef struct _OciRuntime__StartContainerResponse OciRuntime__StartContainerResponse;
typedef struct _OciRuntime__StopContainerRequest OciRuntime__StopContainerRequest;
typedef struct _OciRuntime__StopContainerResponse OciRuntime__StopContainerResponse;
typedef struct _OciRuntime__DeleteContainerRequest OciRuntime__DeleteContainerRequest;
typedef struct _OciRuntime__DeleteContainerResponse OciRuntime__DeleteContainerResponse;
typedef struct _OciRuntime__StateRequest OciRuntime__StateRequest;
typedef struct _OciRuntime__StateResponse OciRuntime__StateResponse;
typedef struct _OciRuntime__StateResponse__AnnotationsEntry OciRuntime__StateResponse__AnnotationsEntry;


/* --- enums --- */


/* --- messages --- */

struct  _OciRuntime__CreateContainerRequest
{
  ProtobufCMessage base;
  char *id;
  char *bundle;
};
#define OCI_RUNTIME__CREATE_CONTAINER_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oci_runtime__create_container_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _OciRuntime__CreateContainerResponse
{
  ProtobufCMessage base;
  char *container_id;
};
#define OCI_RUNTIME__CREATE_CONTAINER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oci_runtime__create_container_response__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _OciRuntime__StartContainerRequest
{
  ProtobufCMessage base;
  char *id;
};
#define OCI_RUNTIME__START_CONTAINER_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oci_runtime__start_container_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _OciRuntime__StartContainerResponse
{
  ProtobufCMessage base;
};
#define OCI_RUNTIME__START_CONTAINER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oci_runtime__start_container_response__descriptor) \
     }


struct  _OciRuntime__StopContainerRequest
{
  ProtobufCMessage base;
  char *id;
  int64_t timeout;
};
#define OCI_RUNTIME__STOP_CONTAINER_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oci_runtime__stop_container_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _OciRuntime__StopContainerResponse
{
  ProtobufCMessage base;
};
#define OCI_RUNTIME__STOP_CONTAINER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oci_runtime__stop_container_response__descriptor) \
     }


struct  _OciRuntime__DeleteContainerRequest
{
  ProtobufCMessage base;
  char *id;
};
#define OCI_RUNTIME__DELETE_CONTAINER_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oci_runtime__delete_container_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _OciRuntime__DeleteContainerResponse
{
  ProtobufCMessage base;
};
#define OCI_RUNTIME__DELETE_CONTAINER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oci_runtime__delete_container_response__descriptor) \
     }


struct  _OciRuntime__StateRequest
{
  ProtobufCMessage base;
  char *id;
};
#define OCI_RUNTIME__STATE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oci_runtime__state_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _OciRuntime__StateResponse__AnnotationsEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define OCI_RUNTIME__STATE_RESPONSE__ANNOTATIONS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oci_runtime__state_response__annotations_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _OciRuntime__StateResponse
{
  ProtobufCMessage base;
  char *id;
  char *status;
  int32_t pid;
  char *bundle;
  size_t n_annotations;
  OciRuntime__StateResponse__AnnotationsEntry **annotations;
};
#define OCI_RUNTIME__STATE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oci_runtime__state_response__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0,NULL }


/* OciRuntime__CreateContainerRequest methods */
void   oci_runtime__create_container_request__init
                     (OciRuntime__CreateContainerRequest         *message);
size_t oci_runtime__create_container_request__get_packed_size
                     (const OciRuntime__CreateContainerRequest   *message);
size_t oci_runtime__create_container_request__pack
                     (const OciRuntime__CreateContainerRequest   *message,
                      uint8_t             *out);
size_t oci_runtime__create_container_request__pack_to_buffer
                     (const OciRuntime__CreateContainerRequest   *message,
                      ProtobufCBuffer     *buffer);
OciRuntime__CreateContainerRequest *
       oci_runtime__create_container_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oci_runtime__create_container_request__free_unpacked
                     (OciRuntime__CreateContainerRequest *message,
                      ProtobufCAllocator *allocator);
/* OciRuntime__CreateContainerResponse methods */
void   oci_runtime__create_container_response__init
                     (OciRuntime__CreateContainerResponse         *message);
size_t oci_runtime__create_container_response__get_packed_size
                     (const OciRuntime__CreateContainerResponse   *message);
size_t oci_runtime__create_container_response__pack
                     (const OciRuntime__CreateContainerResponse   *message,
                      uint8_t             *out);
size_t oci_runtime__create_container_response__pack_to_buffer
                     (const OciRuntime__CreateContainerResponse   *message,
                      ProtobufCBuffer     *buffer);
OciRuntime__CreateContainerResponse *
       oci_runtime__create_container_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oci_runtime__create_container_response__free_unpacked
                     (OciRuntime__CreateContainerResponse *message,
                      ProtobufCAllocator *allocator);
/* OciRuntime__StartContainerRequest methods */
void   oci_runtime__start_container_request__init
                     (OciRuntime__StartContainerRequest         *message);
size_t oci_runtime__start_container_request__get_packed_size
                     (const OciRuntime__StartContainerRequest   *message);
size_t oci_runtime__start_container_request__pack
                     (const OciRuntime__StartContainerRequest   *message,
                      uint8_t             *out);
size_t oci_runtime__start_container_request__pack_to_buffer
                     (const OciRuntime__StartContainerRequest   *message,
                      ProtobufCBuffer     *buffer);
OciRuntime__StartContainerRequest *
       oci_runtime__start_container_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oci_runtime__start_container_request__free_unpacked
                     (OciRuntime__StartContainerRequest *message,
                      ProtobufCAllocator *allocator);
/* OciRuntime__StartContainerResponse methods */
void   oci_runtime__start_container_response__init
                     (OciRuntime__StartContainerResponse         *message);
size_t oci_runtime__start_container_response__get_packed_size
                     (const OciRuntime__StartContainerResponse   *message);
size_t oci_runtime__start_container_response__pack
                     (const OciRuntime__StartContainerResponse   *message,
                      uint8_t             *out);
size_t oci_runtime__start_container_response__pack_to_buffer
                     (const OciRuntime__StartContainerResponse   *message,
                      ProtobufCBuffer     *buffer);
OciRuntime__StartContainerResponse *
       oci_runtime__start_container_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oci_runtime__start_container_response__free_unpacked
                     (OciRuntime__StartContainerResponse *message,
                      ProtobufCAllocator *allocator);
/* OciRuntime__StopContainerRequest methods */
void   oci_runtime__stop_container_request__init
                     (OciRuntime__StopContainerRequest         *message);
size_t oci_runtime__stop_container_request__get_packed_size
                     (const OciRuntime__StopContainerRequest   *message);
size_t oci_runtime__stop_container_request__pack
                     (const OciRuntime__StopContainerRequest   *message,
                      uint8_t             *out);
size_t oci_runtime__stop_container_request__pack_to_buffer
                     (const OciRuntime__StopContainerRequest   *message,
                      ProtobufCBuffer     *buffer);
OciRuntime__StopContainerRequest *
       oci_runtime__stop_container_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oci_runtime__stop_container_request__free_unpacked
                     (OciRuntime__StopContainerRequest *message,
                      ProtobufCAllocator *allocator);
/* OciRuntime__StopContainerResponse methods */
void   oci_runtime__stop_container_response__init
                     (OciRuntime__StopContainerResponse         *message);
size_t oci_runtime__stop_container_response__get_packed_size
                     (const OciRuntime__StopContainerResponse   *message);
size_t oci_runtime__stop_container_response__pack
                     (const OciRuntime__StopContainerResponse   *message,
                      uint8_t             *out);
size_t oci_runtime__stop_container_response__pack_to_buffer
                     (const OciRuntime__StopContainerResponse   *message,
                      ProtobufCBuffer     *buffer);
OciRuntime__StopContainerResponse *
       oci_runtime__stop_container_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oci_runtime__stop_container_response__free_unpacked
                     (OciRuntime__StopContainerResponse *message,
                      ProtobufCAllocator *allocator);
/* OciRuntime__DeleteContainerRequest methods */
void   oci_runtime__delete_container_request__init
                     (OciRuntime__DeleteContainerRequest         *message);
size_t oci_runtime__delete_container_request__get_packed_size
                     (const OciRuntime__DeleteContainerRequest   *message);
size_t oci_runtime__delete_container_request__pack
                     (const OciRuntime__DeleteContainerRequest   *message,
                      uint8_t             *out);
size_t oci_runtime__delete_container_request__pack_to_buffer
                     (const OciRuntime__DeleteContainerRequest   *message,
                      ProtobufCBuffer     *buffer);
OciRuntime__DeleteContainerRequest *
       oci_runtime__delete_container_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oci_runtime__delete_container_request__free_unpacked
                     (OciRuntime__DeleteContainerRequest *message,
                      ProtobufCAllocator *allocator);
/* OciRuntime__DeleteContainerResponse methods */
void   oci_runtime__delete_container_response__init
                     (OciRuntime__DeleteContainerResponse         *message);
size_t oci_runtime__delete_container_response__get_packed_size
                     (const OciRuntime__DeleteContainerResponse   *message);
size_t oci_runtime__delete_container_response__pack
                     (const OciRuntime__DeleteContainerResponse   *message,
                      uint8_t             *out);
size_t oci_runtime__delete_container_response__pack_to_buffer
                     (const OciRuntime__DeleteContainerResponse   *message,
                      ProtobufCBuffer     *buffer);
OciRuntime__DeleteContainerResponse *
       oci_runtime__delete_container_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oci_runtime__delete_container_response__free_unpacked
                     (OciRuntime__DeleteContainerResponse *message,
                      ProtobufCAllocator *allocator);
/* OciRuntime__StateRequest methods */
void   oci_runtime__state_request__init
                     (OciRuntime__StateRequest         *message);
size_t oci_runtime__state_request__get_packed_size
                     (const OciRuntime__StateRequest   *message);
size_t oci_runtime__state_request__pack
                     (const OciRuntime__StateRequest   *message,
                      uint8_t             *out);
size_t oci_runtime__state_request__pack_to_buffer
                     (const OciRuntime__StateRequest   *message,
                      ProtobufCBuffer     *buffer);
OciRuntime__StateRequest *
       oci_runtime__state_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oci_runtime__state_request__free_unpacked
                     (OciRuntime__StateRequest *message,
                      ProtobufCAllocator *allocator);
/* OciRuntime__StateResponse__AnnotationsEntry methods */
void   oci_runtime__state_response__annotations_entry__init
                     (OciRuntime__StateResponse__AnnotationsEntry         *message);
/* OciRuntime__StateResponse methods */
void   oci_runtime__state_response__init
                     (OciRuntime__StateResponse         *message);
size_t oci_runtime__state_response__get_packed_size
                     (const OciRuntime__StateResponse   *message);
size_t oci_runtime__state_response__pack
                     (const OciRuntime__StateResponse   *message,
                      uint8_t             *out);
size_t oci_runtime__state_response__pack_to_buffer
                     (const OciRuntime__StateResponse   *message,
                      ProtobufCBuffer     *buffer);
OciRuntime__StateResponse *
       oci_runtime__state_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oci_runtime__state_response__free_unpacked
                     (OciRuntime__StateResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*OciRuntime__CreateContainerRequest_Closure)
                 (const OciRuntime__CreateContainerRequest *message,
                  void *closure_data);
typedef void (*OciRuntime__CreateContainerResponse_Closure)
                 (const OciRuntime__CreateContainerResponse *message,
                  void *closure_data);
typedef void (*OciRuntime__StartContainerRequest_Closure)
                 (const OciRuntime__StartContainerRequest *message,
                  void *closure_data);
typedef void (*OciRuntime__StartContainerResponse_Closure)
                 (const OciRuntime__StartContainerResponse *message,
                  void *closure_data);
typedef void (*OciRuntime__StopContainerRequest_Closure)
                 (const OciRuntime__StopContainerRequest *message,
                  void *closure_data);
typedef void (*OciRuntime__StopContainerResponse_Closure)
                 (const OciRuntime__StopContainerResponse *message,
                  void *closure_data);
typedef void (*OciRuntime__DeleteContainerRequest_Closure)
                 (const OciRuntime__DeleteContainerRequest *message,
                  void *closure_data);
typedef void (*OciRuntime__DeleteContainerResponse_Closure)
                 (const OciRuntime__DeleteContainerResponse *message,
                  void *closure_data);
typedef void (*OciRuntime__StateRequest_Closure)
                 (const OciRuntime__StateRequest *message,
                  void *closure_data);
typedef void (*OciRuntime__StateResponse__AnnotationsEntry_Closure)
                 (const OciRuntime__StateResponse__AnnotationsEntry *message,
                  void *closure_data);
typedef void (*OciRuntime__StateResponse_Closure)
                 (const OciRuntime__StateResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct _OciRuntime__Runtime_Service OciRuntime__Runtime_Service;
struct _OciRuntime__Runtime_Service
{
  ProtobufCService base;
  void (*create_container)(OciRuntime__Runtime_Service *service,
                           const OciRuntime__CreateContainerRequest *input,
                           OciRuntime__CreateContainerResponse_Closure closure,
                           void *closure_data);
  void (*start_container)(OciRuntime__Runtime_Service *service,
                          const OciRuntime__StartContainerRequest *input,
                          OciRuntime__StartContainerResponse_Closure closure,
                          void *closure_data);
  void (*stop_container)(OciRuntime__Runtime_Service *service,
                         const OciRuntime__StopContainerRequest *input,
                         OciRuntime__StopContainerResponse_Closure closure,
                         void *closure_data);
  void (*delete_container)(OciRuntime__Runtime_Service *service,
                           const OciRuntime__DeleteContainerRequest *input,
                           OciRuntime__DeleteContainerResponse_Closure closure,
                           void *closure_data);
  void (*state)(OciRuntime__Runtime_Service *service,
                const OciRuntime__StateRequest *input,
                OciRuntime__StateResponse_Closure closure,
                void *closure_data);
};
typedef void (*OciRuntime__Runtime_ServiceDestroy)(OciRuntime__Runtime_Service *);
void oci_runtime__runtime__init (OciRuntime__Runtime_Service *service,
                                 OciRuntime__Runtime_ServiceDestroy destroy);
#define OCI_RUNTIME__RUNTIME__BASE_INIT \
    { &oci_runtime__runtime__descriptor, protobuf_c_service_invoke_internal, NULL }
#define OCI_RUNTIME__RUNTIME__INIT(function_prefix__) \
    { OCI_RUNTIME__RUNTIME__BASE_INIT,\
      function_prefix__ ## create_container,\
      function_prefix__ ## start_container,\
      function_prefix__ ## stop_container,\
      function_prefix__ ## delete_container,\
      function_prefix__ ## state  }
void oci_runtime__runtime__create_container(ProtobufCService *service,
                                            const OciRuntime__CreateContainerRequest *input,
                                            OciRuntime__CreateContainerResponse_Closure closure,
                                            void *closure_data);
void oci_runtime__runtime__start_container(ProtobufCService *service,
                                           const OciRuntime__StartContainerRequest *input,
                                           OciRuntime__StartContainerResponse_Closure closure,
                                           void *closure_data);
void oci_runtime__runtime__stop_container(ProtobufCService *service,
                                          const OciRuntime__StopContainerRequest *input,
                                          OciRuntime__StopContainerResponse_Closure closure,
                                          void *closure_data);
void oci_runtime__runtime__delete_container(ProtobufCService *service,
                                            const OciRuntime__DeleteContainerRequest *input,
                                            OciRuntime__DeleteContainerResponse_Closure closure,
                                            void *closure_data);
void oci_runtime__runtime__state(ProtobufCService *service,
                                 const OciRuntime__StateRequest *input,
                                 OciRuntime__StateResponse_Closure closure,
                                 void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor oci_runtime__create_container_request__descriptor;
extern const ProtobufCMessageDescriptor oci_runtime__create_container_response__descriptor;
extern const ProtobufCMessageDescriptor oci_runtime__start_container_request__descriptor;
extern const ProtobufCMessageDescriptor oci_runtime__start_container_response__descriptor;
extern const ProtobufCMessageDescriptor oci_runtime__stop_container_request__descriptor;
extern const ProtobufCMessageDescriptor oci_runtime__stop_container_response__descriptor;
extern const ProtobufCMessageDescriptor oci_runtime__delete_container_request__descriptor;
extern const ProtobufCMessageDescriptor oci_runtime__delete_container_response__descriptor;
extern const ProtobufCMessageDescriptor oci_runtime__state_request__descriptor;
extern const ProtobufCMessageDescriptor oci_runtime__state_response__descriptor;
extern const ProtobufCMessageDescriptor oci_runtime__state_response__annotations_entry__descriptor;
extern const ProtobufCServiceDescriptor oci_runtime__runtime__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2foci_5fruntime_2eproto__INCLUDED */
