/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/oci_runtime.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/oci_runtime.pb-c.h"
void   oci_runtime__create_container_request__init
                     (OciRuntime__CreateContainerRequest         *message)
{
  static const OciRuntime__CreateContainerRequest init_value = OCI_RUNTIME__CREATE_CONTAINER_REQUEST__INIT;
  *message = init_value;
}
size_t oci_runtime__create_container_request__get_packed_size
                     (const OciRuntime__CreateContainerRequest *message)
{
  assert(message->base.descriptor == &oci_runtime__create_container_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oci_runtime__create_container_request__pack
                     (const OciRuntime__CreateContainerRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oci_runtime__create_container_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oci_runtime__create_container_request__pack_to_buffer
                     (const OciRuntime__CreateContainerRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oci_runtime__create_container_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OciRuntime__CreateContainerRequest *
       oci_runtime__create_container_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OciRuntime__CreateContainerRequest *)
     protobuf_c_message_unpack (&oci_runtime__create_container_request__descriptor,
                                allocator, len, data);
}
void   oci_runtime__create_container_request__free_unpacked
                     (OciRuntime__CreateContainerRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oci_runtime__create_container_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oci_runtime__create_container_response__init
                     (OciRuntime__CreateContainerResponse         *message)
{
  static const OciRuntime__CreateContainerResponse init_value = OCI_RUNTIME__CREATE_CONTAINER_RESPONSE__INIT;
  *message = init_value;
}
size_t oci_runtime__create_container_response__get_packed_size
                     (const OciRuntime__CreateContainerResponse *message)
{
  assert(message->base.descriptor == &oci_runtime__create_container_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oci_runtime__create_container_response__pack
                     (const OciRuntime__CreateContainerResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oci_runtime__create_container_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oci_runtime__create_container_response__pack_to_buffer
                     (const OciRuntime__CreateContainerResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oci_runtime__create_container_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OciRuntime__CreateContainerResponse *
       oci_runtime__create_container_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OciRuntime__CreateContainerResponse *)
     protobuf_c_message_unpack (&oci_runtime__create_container_response__descriptor,
                                allocator, len, data);
}
void   oci_runtime__create_container_response__free_unpacked
                     (OciRuntime__CreateContainerResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oci_runtime__create_container_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oci_runtime__start_container_request__init
                     (OciRuntime__StartContainerRequest         *message)
{
  static const OciRuntime__StartContainerRequest init_value = OCI_RUNTIME__START_CONTAINER_REQUEST__INIT;
  *message = init_value;
}
size_t oci_runtime__start_container_request__get_packed_size
                     (const OciRuntime__StartContainerRequest *message)
{
  assert(message->base.descriptor == &oci_runtime__start_container_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oci_runtime__start_container_request__pack
                     (const OciRuntime__StartContainerRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oci_runtime__start_container_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oci_runtime__start_container_request__pack_to_buffer
                     (const OciRuntime__StartContainerRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oci_runtime__start_container_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OciRuntime__StartContainerRequest *
       oci_runtime__start_container_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OciRuntime__StartContainerRequest *)
     protobuf_c_message_unpack (&oci_runtime__start_container_request__descriptor,
                                allocator, len, data);
}
void   oci_runtime__start_container_request__free_unpacked
                     (OciRuntime__StartContainerRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oci_runtime__start_container_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oci_runtime__start_container_response__init
                     (OciRuntime__StartContainerResponse         *message)
{
  static const OciRuntime__StartContainerResponse init_value = OCI_RUNTIME__START_CONTAINER_RESPONSE__INIT;
  *message = init_value;
}
size_t oci_runtime__start_container_response__get_packed_size
                     (const OciRuntime__StartContainerResponse *message)
{
  assert(message->base.descriptor == &oci_runtime__start_container_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oci_runtime__start_container_response__pack
                     (const OciRuntime__StartContainerResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oci_runtime__start_container_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oci_runtime__start_container_response__pack_to_buffer
                     (const OciRuntime__StartContainerResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oci_runtime__start_container_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OciRuntime__StartContainerResponse *
       oci_runtime__start_container_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OciRuntime__StartContainerResponse *)
     protobuf_c_message_unpack (&oci_runtime__start_container_response__descriptor,
                                allocator, len, data);
}
void   oci_runtime__start_container_response__free_unpacked
                     (OciRuntime__StartContainerResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oci_runtime__start_container_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oci_runtime__stop_container_request__init
                     (OciRuntime__StopContainerRequest         *message)
{
  static const OciRuntime__StopContainerRequest init_value = OCI_RUNTIME__STOP_CONTAINER_REQUEST__INIT;
  *message = init_value;
}
size_t oci_runtime__stop_container_request__get_packed_size
                     (const OciRuntime__StopContainerRequest *message)
{
  assert(message->base.descriptor == &oci_runtime__stop_container_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oci_runtime__stop_container_request__pack
                     (const OciRuntime__StopContainerRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oci_runtime__stop_container_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oci_runtime__stop_container_request__pack_to_buffer
                     (const OciRuntime__StopContainerRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oci_runtime__stop_container_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OciRuntime__StopContainerRequest *
       oci_runtime__stop_container_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OciRuntime__StopContainerRequest *)
     protobuf_c_message_unpack (&oci_runtime__stop_container_request__descriptor,
                                allocator, len, data);
}
void   oci_runtime__stop_container_request__free_unpacked
                     (OciRuntime__StopContainerRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oci_runtime__stop_container_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oci_runtime__stop_container_response__init
                     (OciRuntime__StopContainerResponse         *message)
{
  static const OciRuntime__StopContainerResponse init_value = OCI_RUNTIME__STOP_CONTAINER_RESPONSE__INIT;
  *message = init_value;
}
size_t oci_runtime__stop_container_response__get_packed_size
                     (const OciRuntime__StopContainerResponse *message)
{
  assert(message->base.descriptor == &oci_runtime__stop_container_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oci_runtime__stop_container_response__pack
                     (const OciRuntime__StopContainerResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oci_runtime__stop_container_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oci_runtime__stop_container_response__pack_to_buffer
                     (const OciRuntime__StopContainerResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oci_runtime__stop_container_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OciRuntime__StopContainerResponse *
       oci_runtime__stop_container_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OciRuntime__StopContainerResponse *)
     protobuf_c_message_unpack (&oci_runtime__stop_container_response__descriptor,
                                allocator, len, data);
}
void   oci_runtime__stop_container_response__free_unpacked
                     (OciRuntime__StopContainerResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oci_runtime__stop_container_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oci_runtime__delete_container_request__init
                     (OciRuntime__DeleteContainerRequest         *message)
{
  static const OciRuntime__DeleteContainerRequest init_value = OCI_RUNTIME__DELETE_CONTAINER_REQUEST__INIT;
  *message = init_value;
}
size_t oci_runtime__delete_container_request__get_packed_size
                     (const OciRuntime__DeleteContainerRequest *message)
{
  assert(message->base.descriptor == &oci_runtime__delete_container_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oci_runtime__delete_container_request__pack
                     (const OciRuntime__DeleteContainerRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oci_runtime__delete_container_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oci_runtime__delete_container_request__pack_to_buffer
                     (const OciRuntime__DeleteContainerRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oci_runtime__delete_container_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OciRuntime__DeleteContainerRequest *
       oci_runtime__delete_container_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OciRuntime__DeleteContainerRequest *)
     protobuf_c_message_unpack (&oci_runtime__delete_container_request__descriptor,
                                allocator, len, data);
}
void   oci_runtime__delete_container_request__free_unpacked
                     (OciRuntime__DeleteContainerRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oci_runtime__delete_container_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oci_runtime__delete_container_response__init
                     (OciRuntime__DeleteContainerResponse         *message)
{
  static const OciRuntime__DeleteContainerResponse init_value = OCI_RUNTIME__DELETE_CONTAINER_RESPONSE__INIT;
  *message = init_value;
}
size_t oci_runtime__delete_container_response__get_packed_size
                     (const OciRuntime__DeleteContainerResponse *message)
{
  assert(message->base.descriptor == &oci_runtime__delete_container_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oci_runtime__delete_container_response__pack
                     (const OciRuntime__DeleteContainerResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oci_runtime__delete_container_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oci_runtime__delete_container_response__pack_to_buffer
                     (const OciRuntime__DeleteContainerResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oci_runtime__delete_container_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OciRuntime__DeleteContainerResponse *
       oci_runtime__delete_container_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OciRuntime__DeleteContainerResponse *)
     protobuf_c_message_unpack (&oci_runtime__delete_container_response__descriptor,
                                allocator, len, data);
}
void   oci_runtime__delete_container_response__free_unpacked
                     (OciRuntime__DeleteContainerResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oci_runtime__delete_container_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oci_runtime__state_request__init
                     (OciRuntime__StateRequest         *message)
{
  static const OciRuntime__StateRequest init_value = OCI_RUNTIME__STATE_REQUEST__INIT;
  *message = init_value;
}
size_t oci_runtime__state_request__get_packed_size
                     (const OciRuntime__StateRequest *message)
{
  assert(message->base.descriptor == &oci_runtime__state_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oci_runtime__state_request__pack
                     (const OciRuntime__StateRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oci_runtime__state_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oci_runtime__state_request__pack_to_buffer
                     (const OciRuntime__StateRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oci_runtime__state_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OciRuntime__StateRequest *
       oci_runtime__state_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OciRuntime__StateRequest *)
     protobuf_c_message_unpack (&oci_runtime__state_request__descriptor,
                                allocator, len, data);
}
void   oci_runtime__state_request__free_unpacked
                     (OciRuntime__StateRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oci_runtime__state_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oci_runtime__state_response__annotations_entry__init
                     (OciRuntime__StateResponse__AnnotationsEntry         *message)
{
  static const OciRuntime__StateResponse__AnnotationsEntry init_value = OCI_RUNTIME__STATE_RESPONSE__ANNOTATIONS_ENTRY__INIT;
  *message = init_value;
}
void   oci_runtime__state_response__init
                     (OciRuntime__StateResponse         *message)
{
  static const OciRuntime__StateResponse init_value = OCI_RUNTIME__STATE_RESPONSE__INIT;
  *message = init_value;
}
size_t oci_runtime__state_response__get_packed_size
                     (const OciRuntime__StateResponse *message)
{
  assert(message->base.descriptor == &oci_runtime__state_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oci_runtime__state_response__pack
                     (const OciRuntime__StateResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oci_runtime__state_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oci_runtime__state_response__pack_to_buffer
                     (const OciRuntime__StateResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oci_runtime__state_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OciRuntime__StateResponse *
       oci_runtime__state_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OciRuntime__StateResponse *)
     protobuf_c_message_unpack (&oci_runtime__state_response__descriptor,
                                allocator, len, data);
}
void   oci_runtime__state_response__free_unpacked
                     (OciRuntime__StateResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oci_runtime__state_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor oci_runtime__create_container_request__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__CreateContainerRequest, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bundle",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__CreateContainerRequest, bundle),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oci_runtime__create_container_request__field_indices_by_name[] = {
  1,   /* field[1] = bundle */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange oci_runtime__create_container_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor oci_runtime__create_container_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "oci_runtime.CreateContainerRequest",
  "CreateContainerRequest",
  "OciRuntime__CreateContainerRequest",
  "oci_runtime",
  sizeof(OciRuntime__CreateContainerRequest),
  2,
  oci_runtime__create_container_request__field_descriptors,
  oci_runtime__create_container_request__field_indices_by_name,
  1,  oci_runtime__create_container_request__number_ranges,
  (ProtobufCMessageInit) oci_runtime__create_container_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oci_runtime__create_container_response__field_descriptors[1] =
{
  {
    "container_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__CreateContainerResponse, container_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oci_runtime__create_container_response__field_indices_by_name[] = {
  0,   /* field[0] = container_id */
};
static const ProtobufCIntRange oci_runtime__create_container_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor oci_runtime__create_container_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "oci_runtime.CreateContainerResponse",
  "CreateContainerResponse",
  "OciRuntime__CreateContainerResponse",
  "oci_runtime",
  sizeof(OciRuntime__CreateContainerResponse),
  1,
  oci_runtime__create_container_response__field_descriptors,
  oci_runtime__create_container_response__field_indices_by_name,
  1,  oci_runtime__create_container_response__number_ranges,
  (ProtobufCMessageInit) oci_runtime__create_container_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oci_runtime__start_container_request__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__StartContainerRequest, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oci_runtime__start_container_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange oci_runtime__start_container_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor oci_runtime__start_container_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "oci_runtime.StartContainerRequest",
  "StartContainerRequest",
  "OciRuntime__StartContainerRequest",
  "oci_runtime",
  sizeof(OciRuntime__StartContainerRequest),
  1,
  oci_runtime__start_container_request__field_descriptors,
  oci_runtime__start_container_request__field_indices_by_name,
  1,  oci_runtime__start_container_request__number_ranges,
  (ProtobufCMessageInit) oci_runtime__start_container_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define oci_runtime__start_container_response__field_descriptors NULL
#define oci_runtime__start_container_response__field_indices_by_name NULL
#define oci_runtime__start_container_response__number_ranges NULL
const ProtobufCMessageDescriptor oci_runtime__start_container_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "oci_runtime.StartContainerResponse",
  "StartContainerResponse",
  "OciRuntime__StartContainerResponse",
  "oci_runtime",
  sizeof(OciRuntime__StartContainerResponse),
  0,
  oci_runtime__start_container_response__field_descriptors,
  oci_runtime__start_container_response__field_indices_by_name,
  0,  oci_runtime__start_container_response__number_ranges,
  (ProtobufCMessageInit) oci_runtime__start_container_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oci_runtime__stop_container_request__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__StopContainerRequest, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__StopContainerRequest, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oci_runtime__stop_container_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = timeout */
};
static const ProtobufCIntRange oci_runtime__stop_container_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor oci_runtime__stop_container_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "oci_runtime.StopContainerRequest",
  "StopContainerRequest",
  "OciRuntime__StopContainerRequest",
  "oci_runtime",
  sizeof(OciRuntime__StopContainerRequest),
  2,
  oci_runtime__stop_container_request__field_descriptors,
  oci_runtime__stop_container_request__field_indices_by_name,
  1,  oci_runtime__stop_container_request__number_ranges,
  (ProtobufCMessageInit) oci_runtime__stop_container_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define oci_runtime__stop_container_response__field_descriptors NULL
#define oci_runtime__stop_container_response__field_indices_by_name NULL
#define oci_runtime__stop_container_response__number_ranges NULL
const ProtobufCMessageDescriptor oci_runtime__stop_container_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "oci_runtime.StopContainerResponse",
  "StopContainerResponse",
  "OciRuntime__StopContainerResponse",
  "oci_runtime",
  sizeof(OciRuntime__StopContainerResponse),
  0,
  oci_runtime__stop_container_response__field_descriptors,
  oci_runtime__stop_container_response__field_indices_by_name,
  0,  oci_runtime__stop_container_response__number_ranges,
  (ProtobufCMessageInit) oci_runtime__stop_container_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oci_runtime__delete_container_request__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__DeleteContainerRequest, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oci_runtime__delete_container_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange oci_runtime__delete_container_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor oci_runtime__delete_container_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "oci_runtime.DeleteContainerRequest",
  "DeleteContainerRequest",
  "OciRuntime__DeleteContainerRequest",
  "oci_runtime",
  sizeof(OciRuntime__DeleteContainerRequest),
  1,
  oci_runtime__delete_container_request__field_descriptors,
  oci_runtime__delete_container_request__field_indices_by_name,
  1,  oci_runtime__delete_container_request__number_ranges,
  (ProtobufCMessageInit) oci_runtime__delete_container_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define oci_runtime__delete_container_response__field_descriptors NULL
#define oci_runtime__delete_container_response__field_indices_by_name NULL
#define oci_runtime__delete_container_response__number_ranges NULL
const ProtobufCMessageDescriptor oci_runtime__delete_container_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "oci_runtime.DeleteContainerResponse",
  "DeleteContainerResponse",
  "OciRuntime__DeleteContainerResponse",
  "oci_runtime",
  sizeof(OciRuntime__DeleteContainerResponse),
  0,
  oci_runtime__delete_container_response__field_descriptors,
  oci_runtime__delete_container_response__field_indices_by_name,
  0,  oci_runtime__delete_container_response__number_ranges,
  (ProtobufCMessageInit) oci_runtime__delete_container_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oci_runtime__state_request__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__StateRequest, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oci_runtime__state_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange oci_runtime__state_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor oci_runtime__state_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "oci_runtime.StateRequest",
  "StateRequest",
  "OciRuntime__StateRequest",
  "oci_runtime",
  sizeof(OciRuntime__StateRequest),
  1,
  oci_runtime__state_request__field_descriptors,
  oci_runtime__state_request__field_indices_by_name,
  1,  oci_runtime__state_request__number_ranges,
  (ProtobufCMessageInit) oci_runtime__state_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oci_runtime__state_response__annotations_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__StateResponse__AnnotationsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__StateResponse__AnnotationsEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oci_runtime__state_response__annotations_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange oci_runtime__state_response__annotations_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor oci_runtime__state_response__annotations_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "oci_runtime.StateResponse.AnnotationsEntry",
  "AnnotationsEntry",
  "OciRuntime__StateResponse__AnnotationsEntry",
  "oci_runtime",
  sizeof(OciRuntime__StateResponse__AnnotationsEntry),
  2,
  oci_runtime__state_response__annotations_entry__field_descriptors,
  oci_runtime__state_response__annotations_entry__field_indices_by_name,
  1,  oci_runtime__state_response__annotations_entry__number_ranges,
  (ProtobufCMessageInit) oci_runtime__state_response__annotations_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oci_runtime__state_response__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__StateResponse, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__StateResponse, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__StateResponse, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bundle",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OciRuntime__StateResponse, bundle),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "annotations",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OciRuntime__StateResponse, n_annotations),
    offsetof(OciRuntime__StateResponse, annotations),
    &oci_runtime__state_response__annotations_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oci_runtime__state_response__field_indices_by_name[] = {
  4,   /* field[4] = annotations */
  3,   /* field[3] = bundle */
  0,   /* field[0] = id */
  2,   /* field[2] = pid */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange oci_runtime__state_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor oci_runtime__state_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "oci_runtime.StateResponse",
  "StateResponse",
  "OciRuntime__StateResponse",
  "oci_runtime",
  sizeof(OciRuntime__StateResponse),
  5,
  oci_runtime__state_response__field_descriptors,
  oci_runtime__state_response__field_indices_by_name,
  1,  oci_runtime__state_response__number_ranges,
  (ProtobufCMessageInit) oci_runtime__state_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor oci_runtime__runtime__method_descriptors[5] =
{
  { "CreateContainer", &oci_runtime__create_container_request__descriptor, &oci_runtime__create_container_response__descriptor },
  { "StartContainer", &oci_runtime__start_container_request__descriptor, &oci_runtime__start_container_response__descriptor },
  { "StopContainer", &oci_runtime__stop_container_request__descriptor, &oci_runtime__stop_container_response__descriptor },
  { "DeleteContainer", &oci_runtime__delete_container_request__descriptor, &oci_runtime__delete_container_response__descriptor },
  { "State", &oci_runtime__state_request__descriptor, &oci_runtime__state_response__descriptor },
};
const unsigned oci_runtime__runtime__method_indices_by_name[] = {
  0,        /* CreateContainer */
  3,        /* DeleteContainer */
  1,        /* StartContainer */
  4,        /* State */
  2         /* StopContainer */
};
const ProtobufCServiceDescriptor oci_runtime__runtime__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "oci_runtime.Runtime",
  "Runtime",
  "OciRuntime__Runtime",
  "oci_runtime",
  5,
  oci_runtime__runtime__method_descriptors,
  oci_runtime__runtime__method_indices_by_name
};
void oci_runtime__runtime__create_container(ProtobufCService *service,
                                            const OciRuntime__CreateContainerRequest *input,
                                            OciRuntime__CreateContainerResponse_Closure closure,
                                            void *closure_data)
{
  assert(service->descriptor == &oci_runtime__runtime__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void oci_runtime__runtime__start_container(ProtobufCService *service,
                                           const OciRuntime__StartContainerRequest *input,
                                           OciRuntime__StartContainerResponse_Closure closure,
                                           void *closure_data)
{
  assert(service->descriptor == &oci_runtime__runtime__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void oci_runtime__runtime__stop_container(ProtobufCService *service,
                                          const OciRuntime__StopContainerRequest *input,
                                          OciRuntime__StopContainerResponse_Closure closure,
                                          void *closure_data)
{
  assert(service->descriptor == &oci_runtime__runtime__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void oci_runtime__runtime__delete_container(ProtobufCService *service,
                                            const OciRuntime__DeleteContainerRequest *input,
                                            OciRuntime__DeleteContainerResponse_Closure closure,
                                            void *closure_data)
{
  assert(service->descriptor == &oci_runtime__runtime__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void oci_runtime__runtime__state(ProtobufCService *service,
                                 const OciRuntime__StateRequest *input,
                                 OciRuntime__StateResponse_Closure closure,
                                 void *closure_data)
{
  assert(service->descriptor == &oci_runtime__runtime__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void oci_runtime__runtime__init (OciRuntime__Runtime_Service *service,
                                 OciRuntime__Runtime_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &oci_runtime__runtime__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
