// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/runtime_service.proto

#include "proto/runtime_service.pb.h"
#include "proto/runtime_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace runtime {

static const char* RuntimeService_method_names[] = {
  "/runtime.RuntimeService/CreatePod",
  "/runtime.RuntimeService/DeletePod",
  "/runtime.RuntimeService/ListPods",
  "/runtime.RuntimeService/CreateContainer",
  "/runtime.RuntimeService/DeleteContainer",
  "/runtime.RuntimeService/ListContainers",
};

std::unique_ptr< RuntimeService::Stub> RuntimeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RuntimeService::Stub> stub(new RuntimeService::Stub(channel, options));
  return stub;
}

RuntimeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreatePod_(RuntimeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeletePod_(RuntimeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListPods_(RuntimeService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateContainer_(RuntimeService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteContainer_(RuntimeService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListContainers_(RuntimeService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RuntimeService::Stub::CreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::runtime::CreatePodResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::runtime::CreatePodRequest, ::runtime::CreatePodResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreatePod_, context, request, response);
}

void RuntimeService::Stub::async::CreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest* request, ::runtime::CreatePodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::runtime::CreatePodRequest, ::runtime::CreatePodResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreatePod_, context, request, response, std::move(f));
}

void RuntimeService::Stub::async::CreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest* request, ::runtime::CreatePodResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreatePod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::CreatePodResponse>* RuntimeService::Stub::PrepareAsyncCreatePodRaw(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::runtime::CreatePodResponse, ::runtime::CreatePodRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreatePod_, context, request);
}

::grpc::ClientAsyncResponseReader< ::runtime::CreatePodResponse>* RuntimeService::Stub::AsyncCreatePodRaw(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreatePodRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RuntimeService::Stub::DeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::runtime::DeletePodResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::runtime::DeletePodRequest, ::runtime::DeletePodResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeletePod_, context, request, response);
}

void RuntimeService::Stub::async::DeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest* request, ::runtime::DeletePodResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::runtime::DeletePodRequest, ::runtime::DeletePodResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeletePod_, context, request, response, std::move(f));
}

void RuntimeService::Stub::async::DeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest* request, ::runtime::DeletePodResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeletePod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::DeletePodResponse>* RuntimeService::Stub::PrepareAsyncDeletePodRaw(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::runtime::DeletePodResponse, ::runtime::DeletePodRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeletePod_, context, request);
}

::grpc::ClientAsyncResponseReader< ::runtime::DeletePodResponse>* RuntimeService::Stub::AsyncDeletePodRaw(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeletePodRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RuntimeService::Stub::ListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::runtime::ListPodsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::runtime::ListPodsRequest, ::runtime::ListPodsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListPods_, context, request, response);
}

void RuntimeService::Stub::async::ListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest* request, ::runtime::ListPodsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::runtime::ListPodsRequest, ::runtime::ListPodsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListPods_, context, request, response, std::move(f));
}

void RuntimeService::Stub::async::ListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest* request, ::runtime::ListPodsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListPods_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::ListPodsResponse>* RuntimeService::Stub::PrepareAsyncListPodsRaw(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::runtime::ListPodsResponse, ::runtime::ListPodsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListPods_, context, request);
}

::grpc::ClientAsyncResponseReader< ::runtime::ListPodsResponse>* RuntimeService::Stub::AsyncListPodsRaw(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListPodsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RuntimeService::Stub::CreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::runtime::CreateContainerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::runtime::CreateContainerRequest, ::runtime::CreateContainerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateContainer_, context, request, response);
}

void RuntimeService::Stub::async::CreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest* request, ::runtime::CreateContainerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::runtime::CreateContainerRequest, ::runtime::CreateContainerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateContainer_, context, request, response, std::move(f));
}

void RuntimeService::Stub::async::CreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest* request, ::runtime::CreateContainerResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateContainer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::CreateContainerResponse>* RuntimeService::Stub::PrepareAsyncCreateContainerRaw(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::runtime::CreateContainerResponse, ::runtime::CreateContainerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateContainer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::runtime::CreateContainerResponse>* RuntimeService::Stub::AsyncCreateContainerRaw(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateContainerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RuntimeService::Stub::DeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::runtime::DeleteContainerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::runtime::DeleteContainerRequest, ::runtime::DeleteContainerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteContainer_, context, request, response);
}

void RuntimeService::Stub::async::DeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest* request, ::runtime::DeleteContainerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::runtime::DeleteContainerRequest, ::runtime::DeleteContainerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteContainer_, context, request, response, std::move(f));
}

void RuntimeService::Stub::async::DeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest* request, ::runtime::DeleteContainerResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteContainer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::DeleteContainerResponse>* RuntimeService::Stub::PrepareAsyncDeleteContainerRaw(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::runtime::DeleteContainerResponse, ::runtime::DeleteContainerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteContainer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::runtime::DeleteContainerResponse>* RuntimeService::Stub::AsyncDeleteContainerRaw(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteContainerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RuntimeService::Stub::ListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::runtime::ListContainersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::runtime::ListContainersRequest, ::runtime::ListContainersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListContainers_, context, request, response);
}

void RuntimeService::Stub::async::ListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest* request, ::runtime::ListContainersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::runtime::ListContainersRequest, ::runtime::ListContainersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListContainers_, context, request, response, std::move(f));
}

void RuntimeService::Stub::async::ListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest* request, ::runtime::ListContainersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListContainers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::runtime::ListContainersResponse>* RuntimeService::Stub::PrepareAsyncListContainersRaw(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::runtime::ListContainersResponse, ::runtime::ListContainersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListContainers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::runtime::ListContainersResponse>* RuntimeService::Stub::AsyncListContainersRaw(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListContainersRaw(context, request, cq);
  result->StartCall();
  return result;
}

RuntimeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::CreatePodRequest, ::runtime::CreatePodResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RuntimeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::runtime::CreatePodRequest* req,
             ::runtime::CreatePodResponse* resp) {
               return service->CreatePod(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::DeletePodRequest, ::runtime::DeletePodResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RuntimeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::runtime::DeletePodRequest* req,
             ::runtime::DeletePodResponse* resp) {
               return service->DeletePod(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::ListPodsRequest, ::runtime::ListPodsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RuntimeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::runtime::ListPodsRequest* req,
             ::runtime::ListPodsResponse* resp) {
               return service->ListPods(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::CreateContainerRequest, ::runtime::CreateContainerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RuntimeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::runtime::CreateContainerRequest* req,
             ::runtime::CreateContainerResponse* resp) {
               return service->CreateContainer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::DeleteContainerRequest, ::runtime::DeleteContainerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RuntimeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::runtime::DeleteContainerRequest* req,
             ::runtime::DeleteContainerResponse* resp) {
               return service->DeleteContainer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RuntimeService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RuntimeService::Service, ::runtime::ListContainersRequest, ::runtime::ListContainersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RuntimeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::runtime::ListContainersRequest* req,
             ::runtime::ListContainersResponse* resp) {
               return service->ListContainers(ctx, req, resp);
             }, this)));
}

RuntimeService::Service::~Service() {
}

::grpc::Status RuntimeService::Service::CreatePod(::grpc::ServerContext* context, const ::runtime::CreatePodRequest* request, ::runtime::CreatePodResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::DeletePod(::grpc::ServerContext* context, const ::runtime::DeletePodRequest* request, ::runtime::DeletePodResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::ListPods(::grpc::ServerContext* context, const ::runtime::ListPodsRequest* request, ::runtime::ListPodsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::CreateContainer(::grpc::ServerContext* context, const ::runtime::CreateContainerRequest* request, ::runtime::CreateContainerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::DeleteContainer(::grpc::ServerContext* context, const ::runtime::DeleteContainerRequest* request, ::runtime::DeleteContainerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RuntimeService::Service::ListContainers(::grpc::ServerContext* context, const ::runtime::ListContainersRequest* request, ::runtime::ListContainersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace runtime

