// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/runtime_service.proto
#ifndef GRPC_proto_2fruntime_5fservice_2eproto__INCLUDED
#define GRPC_proto_2fruntime_5fservice_2eproto__INCLUDED

#include "proto/runtime_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace runtime {

// Runtime service defines the public APIs for remote container runtimes
class RuntimeService final {
 public:
  static constexpr char const* service_full_name() {
    return "runtime.RuntimeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Pod management
    virtual ::grpc::Status CreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::runtime::CreatePodResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::CreatePodResponse>> AsyncCreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::CreatePodResponse>>(AsyncCreatePodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::CreatePodResponse>> PrepareAsyncCreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::CreatePodResponse>>(PrepareAsyncCreatePodRaw(context, request, cq));
    }
    virtual ::grpc::Status DeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::runtime::DeletePodResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::DeletePodResponse>> AsyncDeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::DeletePodResponse>>(AsyncDeletePodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::DeletePodResponse>> PrepareAsyncDeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::DeletePodResponse>>(PrepareAsyncDeletePodRaw(context, request, cq));
    }
    virtual ::grpc::Status ListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::runtime::ListPodsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::ListPodsResponse>> AsyncListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::ListPodsResponse>>(AsyncListPodsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::ListPodsResponse>> PrepareAsyncListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::ListPodsResponse>>(PrepareAsyncListPodsRaw(context, request, cq));
    }
    // Container management
    virtual ::grpc::Status CreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::runtime::CreateContainerResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::CreateContainerResponse>> AsyncCreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::CreateContainerResponse>>(AsyncCreateContainerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::CreateContainerResponse>> PrepareAsyncCreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::CreateContainerResponse>>(PrepareAsyncCreateContainerRaw(context, request, cq));
    }
    virtual ::grpc::Status DeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::runtime::DeleteContainerResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::DeleteContainerResponse>> AsyncDeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::DeleteContainerResponse>>(AsyncDeleteContainerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::DeleteContainerResponse>> PrepareAsyncDeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::DeleteContainerResponse>>(PrepareAsyncDeleteContainerRaw(context, request, cq));
    }
    virtual ::grpc::Status ListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::runtime::ListContainersResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::ListContainersResponse>> AsyncListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::ListContainersResponse>>(AsyncListContainersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::ListContainersResponse>> PrepareAsyncListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::runtime::ListContainersResponse>>(PrepareAsyncListContainersRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Pod management
      virtual void CreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest* request, ::runtime::CreatePodResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest* request, ::runtime::CreatePodResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest* request, ::runtime::DeletePodResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest* request, ::runtime::DeletePodResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest* request, ::runtime::ListPodsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest* request, ::runtime::ListPodsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Container management
      virtual void CreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest* request, ::runtime::CreateContainerResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest* request, ::runtime::CreateContainerResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest* request, ::runtime::DeleteContainerResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest* request, ::runtime::DeleteContainerResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest* request, ::runtime::ListContainersResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest* request, ::runtime::ListContainersResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::runtime::CreatePodResponse>* AsyncCreatePodRaw(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::runtime::CreatePodResponse>* PrepareAsyncCreatePodRaw(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::runtime::DeletePodResponse>* AsyncDeletePodRaw(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::runtime::DeletePodResponse>* PrepareAsyncDeletePodRaw(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::runtime::ListPodsResponse>* AsyncListPodsRaw(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::runtime::ListPodsResponse>* PrepareAsyncListPodsRaw(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::runtime::CreateContainerResponse>* AsyncCreateContainerRaw(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::runtime::CreateContainerResponse>* PrepareAsyncCreateContainerRaw(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::runtime::DeleteContainerResponse>* AsyncDeleteContainerRaw(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::runtime::DeleteContainerResponse>* PrepareAsyncDeleteContainerRaw(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::runtime::ListContainersResponse>* AsyncListContainersRaw(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::runtime::ListContainersResponse>* PrepareAsyncListContainersRaw(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::runtime::CreatePodResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::CreatePodResponse>> AsyncCreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::CreatePodResponse>>(AsyncCreatePodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::CreatePodResponse>> PrepareAsyncCreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::CreatePodResponse>>(PrepareAsyncCreatePodRaw(context, request, cq));
    }
    ::grpc::Status DeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::runtime::DeletePodResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::DeletePodResponse>> AsyncDeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::DeletePodResponse>>(AsyncDeletePodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::DeletePodResponse>> PrepareAsyncDeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::DeletePodResponse>>(PrepareAsyncDeletePodRaw(context, request, cq));
    }
    ::grpc::Status ListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::runtime::ListPodsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::ListPodsResponse>> AsyncListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::ListPodsResponse>>(AsyncListPodsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::ListPodsResponse>> PrepareAsyncListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::ListPodsResponse>>(PrepareAsyncListPodsRaw(context, request, cq));
    }
    ::grpc::Status CreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::runtime::CreateContainerResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::CreateContainerResponse>> AsyncCreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::CreateContainerResponse>>(AsyncCreateContainerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::CreateContainerResponse>> PrepareAsyncCreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::CreateContainerResponse>>(PrepareAsyncCreateContainerRaw(context, request, cq));
    }
    ::grpc::Status DeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::runtime::DeleteContainerResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::DeleteContainerResponse>> AsyncDeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::DeleteContainerResponse>>(AsyncDeleteContainerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::DeleteContainerResponse>> PrepareAsyncDeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::DeleteContainerResponse>>(PrepareAsyncDeleteContainerRaw(context, request, cq));
    }
    ::grpc::Status ListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::runtime::ListContainersResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::ListContainersResponse>> AsyncListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::ListContainersResponse>>(AsyncListContainersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::ListContainersResponse>> PrepareAsyncListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::runtime::ListContainersResponse>>(PrepareAsyncListContainersRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest* request, ::runtime::CreatePodResponse* response, std::function<void(::grpc::Status)>) override;
      void CreatePod(::grpc::ClientContext* context, const ::runtime::CreatePodRequest* request, ::runtime::CreatePodResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest* request, ::runtime::DeletePodResponse* response, std::function<void(::grpc::Status)>) override;
      void DeletePod(::grpc::ClientContext* context, const ::runtime::DeletePodRequest* request, ::runtime::DeletePodResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest* request, ::runtime::ListPodsResponse* response, std::function<void(::grpc::Status)>) override;
      void ListPods(::grpc::ClientContext* context, const ::runtime::ListPodsRequest* request, ::runtime::ListPodsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest* request, ::runtime::CreateContainerResponse* response, std::function<void(::grpc::Status)>) override;
      void CreateContainer(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest* request, ::runtime::CreateContainerResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest* request, ::runtime::DeleteContainerResponse* response, std::function<void(::grpc::Status)>) override;
      void DeleteContainer(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest* request, ::runtime::DeleteContainerResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest* request, ::runtime::ListContainersResponse* response, std::function<void(::grpc::Status)>) override;
      void ListContainers(::grpc::ClientContext* context, const ::runtime::ListContainersRequest* request, ::runtime::ListContainersResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::runtime::CreatePodResponse>* AsyncCreatePodRaw(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::runtime::CreatePodResponse>* PrepareAsyncCreatePodRaw(::grpc::ClientContext* context, const ::runtime::CreatePodRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::runtime::DeletePodResponse>* AsyncDeletePodRaw(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::runtime::DeletePodResponse>* PrepareAsyncDeletePodRaw(::grpc::ClientContext* context, const ::runtime::DeletePodRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::runtime::ListPodsResponse>* AsyncListPodsRaw(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::runtime::ListPodsResponse>* PrepareAsyncListPodsRaw(::grpc::ClientContext* context, const ::runtime::ListPodsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::runtime::CreateContainerResponse>* AsyncCreateContainerRaw(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::runtime::CreateContainerResponse>* PrepareAsyncCreateContainerRaw(::grpc::ClientContext* context, const ::runtime::CreateContainerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::runtime::DeleteContainerResponse>* AsyncDeleteContainerRaw(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::runtime::DeleteContainerResponse>* PrepareAsyncDeleteContainerRaw(::grpc::ClientContext* context, const ::runtime::DeleteContainerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::runtime::ListContainersResponse>* AsyncListContainersRaw(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::runtime::ListContainersResponse>* PrepareAsyncListContainersRaw(::grpc::ClientContext* context, const ::runtime::ListContainersRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreatePod_;
    const ::grpc::internal::RpcMethod rpcmethod_DeletePod_;
    const ::grpc::internal::RpcMethod rpcmethod_ListPods_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateContainer_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteContainer_;
    const ::grpc::internal::RpcMethod rpcmethod_ListContainers_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Pod management
    virtual ::grpc::Status CreatePod(::grpc::ServerContext* context, const ::runtime::CreatePodRequest* request, ::runtime::CreatePodResponse* response);
    virtual ::grpc::Status DeletePod(::grpc::ServerContext* context, const ::runtime::DeletePodRequest* request, ::runtime::DeletePodResponse* response);
    virtual ::grpc::Status ListPods(::grpc::ServerContext* context, const ::runtime::ListPodsRequest* request, ::runtime::ListPodsResponse* response);
    // Container management
    virtual ::grpc::Status CreateContainer(::grpc::ServerContext* context, const ::runtime::CreateContainerRequest* request, ::runtime::CreateContainerResponse* response);
    virtual ::grpc::Status DeleteContainer(::grpc::ServerContext* context, const ::runtime::DeleteContainerRequest* request, ::runtime::DeleteContainerResponse* response);
    virtual ::grpc::Status ListContainers(::grpc::ServerContext* context, const ::runtime::ListContainersRequest* request, ::runtime::ListContainersResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreatePod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreatePod() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreatePod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreatePod(::grpc::ServerContext* /*context*/, const ::runtime::CreatePodRequest* /*request*/, ::runtime::CreatePodResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreatePod(::grpc::ServerContext* context, ::runtime::CreatePodRequest* request, ::grpc::ServerAsyncResponseWriter< ::runtime::CreatePodResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeletePod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeletePod() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_DeletePod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeletePod(::grpc::ServerContext* /*context*/, const ::runtime::DeletePodRequest* /*request*/, ::runtime::DeletePodResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeletePod(::grpc::ServerContext* context, ::runtime::DeletePodRequest* request, ::grpc::ServerAsyncResponseWriter< ::runtime::DeletePodResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListPods : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListPods() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ListPods() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPods(::grpc::ServerContext* /*context*/, const ::runtime::ListPodsRequest* /*request*/, ::runtime::ListPodsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListPods(::grpc::ServerContext* context, ::runtime::ListPodsRequest* request, ::grpc::ServerAsyncResponseWriter< ::runtime::ListPodsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateContainer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateContainer() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_CreateContainer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContainer(::grpc::ServerContext* /*context*/, const ::runtime::CreateContainerRequest* /*request*/, ::runtime::CreateContainerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateContainer(::grpc::ServerContext* context, ::runtime::CreateContainerRequest* request, ::grpc::ServerAsyncResponseWriter< ::runtime::CreateContainerResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteContainer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteContainer() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_DeleteContainer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContainer(::grpc::ServerContext* /*context*/, const ::runtime::DeleteContainerRequest* /*request*/, ::runtime::DeleteContainerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteContainer(::grpc::ServerContext* context, ::runtime::DeleteContainerRequest* request, ::grpc::ServerAsyncResponseWriter< ::runtime::DeleteContainerResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListContainers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListContainers() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_ListContainers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContainers(::grpc::ServerContext* /*context*/, const ::runtime::ListContainersRequest* /*request*/, ::runtime::ListContainersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListContainers(::grpc::ServerContext* context, ::runtime::ListContainersRequest* request, ::grpc::ServerAsyncResponseWriter< ::runtime::ListContainersResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreatePod<WithAsyncMethod_DeletePod<WithAsyncMethod_ListPods<WithAsyncMethod_CreateContainer<WithAsyncMethod_DeleteContainer<WithAsyncMethod_ListContainers<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CreatePod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreatePod() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::runtime::CreatePodRequest, ::runtime::CreatePodResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::runtime::CreatePodRequest* request, ::runtime::CreatePodResponse* response) { return this->CreatePod(context, request, response); }));}
    void SetMessageAllocatorFor_CreatePod(
        ::grpc::MessageAllocator< ::runtime::CreatePodRequest, ::runtime::CreatePodResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::runtime::CreatePodRequest, ::runtime::CreatePodResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreatePod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreatePod(::grpc::ServerContext* /*context*/, const ::runtime::CreatePodRequest* /*request*/, ::runtime::CreatePodResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreatePod(
      ::grpc::CallbackServerContext* /*context*/, const ::runtime::CreatePodRequest* /*request*/, ::runtime::CreatePodResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeletePod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeletePod() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::runtime::DeletePodRequest, ::runtime::DeletePodResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::runtime::DeletePodRequest* request, ::runtime::DeletePodResponse* response) { return this->DeletePod(context, request, response); }));}
    void SetMessageAllocatorFor_DeletePod(
        ::grpc::MessageAllocator< ::runtime::DeletePodRequest, ::runtime::DeletePodResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::runtime::DeletePodRequest, ::runtime::DeletePodResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeletePod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeletePod(::grpc::ServerContext* /*context*/, const ::runtime::DeletePodRequest* /*request*/, ::runtime::DeletePodResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeletePod(
      ::grpc::CallbackServerContext* /*context*/, const ::runtime::DeletePodRequest* /*request*/, ::runtime::DeletePodResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListPods : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListPods() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::runtime::ListPodsRequest, ::runtime::ListPodsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::runtime::ListPodsRequest* request, ::runtime::ListPodsResponse* response) { return this->ListPods(context, request, response); }));}
    void SetMessageAllocatorFor_ListPods(
        ::grpc::MessageAllocator< ::runtime::ListPodsRequest, ::runtime::ListPodsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::runtime::ListPodsRequest, ::runtime::ListPodsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListPods() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPods(::grpc::ServerContext* /*context*/, const ::runtime::ListPodsRequest* /*request*/, ::runtime::ListPodsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListPods(
      ::grpc::CallbackServerContext* /*context*/, const ::runtime::ListPodsRequest* /*request*/, ::runtime::ListPodsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CreateContainer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateContainer() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::runtime::CreateContainerRequest, ::runtime::CreateContainerResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::runtime::CreateContainerRequest* request, ::runtime::CreateContainerResponse* response) { return this->CreateContainer(context, request, response); }));}
    void SetMessageAllocatorFor_CreateContainer(
        ::grpc::MessageAllocator< ::runtime::CreateContainerRequest, ::runtime::CreateContainerResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::runtime::CreateContainerRequest, ::runtime::CreateContainerResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateContainer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContainer(::grpc::ServerContext* /*context*/, const ::runtime::CreateContainerRequest* /*request*/, ::runtime::CreateContainerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateContainer(
      ::grpc::CallbackServerContext* /*context*/, const ::runtime::CreateContainerRequest* /*request*/, ::runtime::CreateContainerResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteContainer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteContainer() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::runtime::DeleteContainerRequest, ::runtime::DeleteContainerResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::runtime::DeleteContainerRequest* request, ::runtime::DeleteContainerResponse* response) { return this->DeleteContainer(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteContainer(
        ::grpc::MessageAllocator< ::runtime::DeleteContainerRequest, ::runtime::DeleteContainerResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::runtime::DeleteContainerRequest, ::runtime::DeleteContainerResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteContainer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContainer(::grpc::ServerContext* /*context*/, const ::runtime::DeleteContainerRequest* /*request*/, ::runtime::DeleteContainerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteContainer(
      ::grpc::CallbackServerContext* /*context*/, const ::runtime::DeleteContainerRequest* /*request*/, ::runtime::DeleteContainerResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListContainers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListContainers() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::runtime::ListContainersRequest, ::runtime::ListContainersResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::runtime::ListContainersRequest* request, ::runtime::ListContainersResponse* response) { return this->ListContainers(context, request, response); }));}
    void SetMessageAllocatorFor_ListContainers(
        ::grpc::MessageAllocator< ::runtime::ListContainersRequest, ::runtime::ListContainersResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::runtime::ListContainersRequest, ::runtime::ListContainersResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListContainers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContainers(::grpc::ServerContext* /*context*/, const ::runtime::ListContainersRequest* /*request*/, ::runtime::ListContainersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListContainers(
      ::grpc::CallbackServerContext* /*context*/, const ::runtime::ListContainersRequest* /*request*/, ::runtime::ListContainersResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CreatePod<WithCallbackMethod_DeletePod<WithCallbackMethod_ListPods<WithCallbackMethod_CreateContainer<WithCallbackMethod_DeleteContainer<WithCallbackMethod_ListContainers<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreatePod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreatePod() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreatePod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreatePod(::grpc::ServerContext* /*context*/, const ::runtime::CreatePodRequest* /*request*/, ::runtime::CreatePodResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeletePod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeletePod() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_DeletePod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeletePod(::grpc::ServerContext* /*context*/, const ::runtime::DeletePodRequest* /*request*/, ::runtime::DeletePodResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListPods : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListPods() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ListPods() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPods(::grpc::ServerContext* /*context*/, const ::runtime::ListPodsRequest* /*request*/, ::runtime::ListPodsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateContainer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateContainer() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_CreateContainer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContainer(::grpc::ServerContext* /*context*/, const ::runtime::CreateContainerRequest* /*request*/, ::runtime::CreateContainerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteContainer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteContainer() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_DeleteContainer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContainer(::grpc::ServerContext* /*context*/, const ::runtime::DeleteContainerRequest* /*request*/, ::runtime::DeleteContainerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListContainers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListContainers() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_ListContainers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContainers(::grpc::ServerContext* /*context*/, const ::runtime::ListContainersRequest* /*request*/, ::runtime::ListContainersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreatePod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreatePod() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreatePod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreatePod(::grpc::ServerContext* /*context*/, const ::runtime::CreatePodRequest* /*request*/, ::runtime::CreatePodResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreatePod(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeletePod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeletePod() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_DeletePod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeletePod(::grpc::ServerContext* /*context*/, const ::runtime::DeletePodRequest* /*request*/, ::runtime::DeletePodResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeletePod(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListPods : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListPods() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ListPods() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPods(::grpc::ServerContext* /*context*/, const ::runtime::ListPodsRequest* /*request*/, ::runtime::ListPodsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListPods(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateContainer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateContainer() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_CreateContainer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContainer(::grpc::ServerContext* /*context*/, const ::runtime::CreateContainerRequest* /*request*/, ::runtime::CreateContainerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateContainer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteContainer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteContainer() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_DeleteContainer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContainer(::grpc::ServerContext* /*context*/, const ::runtime::DeleteContainerRequest* /*request*/, ::runtime::DeleteContainerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteContainer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListContainers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListContainers() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_ListContainers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContainers(::grpc::ServerContext* /*context*/, const ::runtime::ListContainersRequest* /*request*/, ::runtime::ListContainersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListContainers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreatePod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreatePod() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreatePod(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreatePod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreatePod(::grpc::ServerContext* /*context*/, const ::runtime::CreatePodRequest* /*request*/, ::runtime::CreatePodResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreatePod(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeletePod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeletePod() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeletePod(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeletePod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeletePod(::grpc::ServerContext* /*context*/, const ::runtime::DeletePodRequest* /*request*/, ::runtime::DeletePodResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeletePod(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListPods : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListPods() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListPods(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListPods() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListPods(::grpc::ServerContext* /*context*/, const ::runtime::ListPodsRequest* /*request*/, ::runtime::ListPodsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListPods(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateContainer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateContainer() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateContainer(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateContainer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContainer(::grpc::ServerContext* /*context*/, const ::runtime::CreateContainerRequest* /*request*/, ::runtime::CreateContainerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateContainer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteContainer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteContainer() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteContainer(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteContainer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContainer(::grpc::ServerContext* /*context*/, const ::runtime::DeleteContainerRequest* /*request*/, ::runtime::DeleteContainerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteContainer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListContainers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListContainers() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListContainers(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListContainers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContainers(::grpc::ServerContext* /*context*/, const ::runtime::ListContainersRequest* /*request*/, ::runtime::ListContainersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListContainers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreatePod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreatePod() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::runtime::CreatePodRequest, ::runtime::CreatePodResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::runtime::CreatePodRequest, ::runtime::CreatePodResponse>* streamer) {
                       return this->StreamedCreatePod(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreatePod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreatePod(::grpc::ServerContext* /*context*/, const ::runtime::CreatePodRequest* /*request*/, ::runtime::CreatePodResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreatePod(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::runtime::CreatePodRequest,::runtime::CreatePodResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeletePod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeletePod() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::runtime::DeletePodRequest, ::runtime::DeletePodResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::runtime::DeletePodRequest, ::runtime::DeletePodResponse>* streamer) {
                       return this->StreamedDeletePod(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeletePod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeletePod(::grpc::ServerContext* /*context*/, const ::runtime::DeletePodRequest* /*request*/, ::runtime::DeletePodResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeletePod(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::runtime::DeletePodRequest,::runtime::DeletePodResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListPods : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListPods() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::runtime::ListPodsRequest, ::runtime::ListPodsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::runtime::ListPodsRequest, ::runtime::ListPodsResponse>* streamer) {
                       return this->StreamedListPods(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListPods() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListPods(::grpc::ServerContext* /*context*/, const ::runtime::ListPodsRequest* /*request*/, ::runtime::ListPodsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListPods(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::runtime::ListPodsRequest,::runtime::ListPodsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateContainer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateContainer() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::runtime::CreateContainerRequest, ::runtime::CreateContainerResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::runtime::CreateContainerRequest, ::runtime::CreateContainerResponse>* streamer) {
                       return this->StreamedCreateContainer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateContainer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateContainer(::grpc::ServerContext* /*context*/, const ::runtime::CreateContainerRequest* /*request*/, ::runtime::CreateContainerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateContainer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::runtime::CreateContainerRequest,::runtime::CreateContainerResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteContainer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteContainer() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::runtime::DeleteContainerRequest, ::runtime::DeleteContainerResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::runtime::DeleteContainerRequest, ::runtime::DeleteContainerResponse>* streamer) {
                       return this->StreamedDeleteContainer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteContainer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteContainer(::grpc::ServerContext* /*context*/, const ::runtime::DeleteContainerRequest* /*request*/, ::runtime::DeleteContainerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteContainer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::runtime::DeleteContainerRequest,::runtime::DeleteContainerResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListContainers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListContainers() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::runtime::ListContainersRequest, ::runtime::ListContainersResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::runtime::ListContainersRequest, ::runtime::ListContainersResponse>* streamer) {
                       return this->StreamedListContainers(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListContainers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListContainers(::grpc::ServerContext* /*context*/, const ::runtime::ListContainersRequest* /*request*/, ::runtime::ListContainersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListContainers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::runtime::ListContainersRequest,::runtime::ListContainersResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreatePod<WithStreamedUnaryMethod_DeletePod<WithStreamedUnaryMethod_ListPods<WithStreamedUnaryMethod_CreateContainer<WithStreamedUnaryMethod_DeleteContainer<WithStreamedUnaryMethod_ListContainers<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreatePod<WithStreamedUnaryMethod_DeletePod<WithStreamedUnaryMethod_ListPods<WithStreamedUnaryMethod_CreateContainer<WithStreamedUnaryMethod_DeleteContainer<WithStreamedUnaryMethod_ListContainers<Service > > > > > > StreamedService;
};

}  // namespace runtime


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_proto_2fruntime_5fservice_2eproto__INCLUDED
